export const REQUEST_NOTIFICATIONS_TOKEN = 'REQUEST_NOTIFICATIONS_TOKEN';
export const REQUEST_NOTIFICATIONS_TOKEN_SUCCESS =
  'REQUEST_NOTIFICATIONS_TOKEN_SUCCESS';
export const REQUEST_NOTIFICATIONS_TOKEN_ERROR =
  'REQUEST_NOTIFICATIONS_TOKEN_ERROR';
