openapi: 3.0.0
info:
  title: Notifications API
  description: Notifications
  version: 1.0.0
servers:
  - url: http://localhost:3001
    description: Local Dev
  - url: https://api-qa.semasoftware.com
    description: QA
  - url: https://api-staging.semasoftware.com
    description: staging
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - bearerAuth: []
paths:
  /v1/notification-token:
    get:
      summary: get notification token
      operationId: getNotificationToken
      responses:
        200:
          content:
            application/json:
              token:
                type: string
          description: notifications token
        400:
          description: bad input parameter