openapi: 3.0.0
info:
  title: Analysis's API
  description: Analysis
  version: 1.0.0
servers:
  - url: http://localhost:3001
    description: Local Dev
  - url: https://api-qa.semasoftware.com
    description: QA
  - url: https://api-staging.semasoftware.com
    description: staging
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - bearerAuth: []
paths:
  /v1/analysis:
    post:
      summary: execute analysis
      operationId: findByProject
      requestBody:
        content:
          application/json:
            schema:
             properties:
              repositoryId:
                type: string
              externalSourceId:
                type: string
              legacyId:
                type: string
      responses:
        200:
          description: executed analysis
        400:
          description: bad input parameter