export const REQUEST_FETCH_SUGGEST_COMMENTS = 'REQUEST_FETCH_SUGGEST_COMMENTS';
export const REQUEST_FETCH_SUGGEST_COMMENTS_SUCCESS = 'REQUEST_FETCH_SUGGEST_COMMENTS_SUCCESS';
export const REQUEST_FETCH_SUGGEST_COMMENTS_ERROR = 'REQUEST_FETCH_SUGGEST_COMMENTS_ERROR';
