export const REQUEST_FETCH_SUGGEST_COMMENTS = 'REQUEST_FETCH_SUGGEST_COMMENTS';
export const REQUEST_FETCH_SUGGEST_COMMENTS_SUCCESS = 'REQUEST_FETCH_SUGGEST_COMMENTS_SUCCESS';
export const REQUEST_FETCH_SUGGEST_COMMENTS_ERROR = 'REQUEST_FETCH_SUGGEST_COMMENTS_ERROR';
export const REQUEST_CREATE_SUGGEST_COMMENT = 'REQUEST_CREATE_SUGGEST_COMMENT';
export const REQUEST_CREATE_SUGGEST_COMMENT_SUCCESS = 'REQUEST_CREATE_SUGGEST_COMMENT_SUCCESS';
export const REQUEST_CREATE_SUGGEST_COMMENT_ERROR = 'REQUEST_CREATE_SUGGEST_COMMENT_ERROR';
