reviewers:
  groups:
    devops-lovers:
      - team:devops # username

files:
  # Keys are glob expressions.
  # You can assign groups defined above as well as GitHub usernames.
  "**/.env":
    - devops-lovers # group
  'terraform/**':
    - devops-lovers # group
  "apollo/migrations/**":
    - devops-lovers # group
  "apollo/scripts/**":
    - devops-lovers # group

options:
  ignore_draft: true
  ignored_keywords:
    - DO NOT REVIEW
  enable_group_assignment: true

  # # Randomly pick reviewers up to this number.
  # # Do not set this option if you'd like to assign all matching reviewers.
  # number_of_reviewers: 3
