FROM node:16-alpine3.14 AS build

WORKDIR /usr/adonis
COPY  ./adonis /usr/adonis
RUN npm i -g npm@8.5.5
RUN npm ci
RUN npm run build

WORKDIR /usr/app
COPY ./web/.env ./
COPY ./web/package*.json ./

ENV PATH /usr/app/node_modules/.bin:$PATH
ENV NODE_ENV development
RUN npm install

EXPOSE 3000

CMD ["npm", "run", "dev"]
