FROM node:12.15.0-alpine

RUN apk add --update --no-cache \
    python \
    make \
    g++
 

RUN mkdir -p /usr/app/  && chown -R node:node /usr/app
USER node

WORKDIR /usr/app
COPY --chown=node:node ./package*.json ./

RUN npm install  
COPY --chown=node:node ./ ./

EXPOSE 3000

CMD ["npm", "run", "dev"]