export const FETCH_ALL_TAGS = 'FETCH_ALL_TAGS';
export const FETCH_ALL_TAGS_SUCCESS = 'FETCH_ALL_TAGS_SUCCESS';
export const FETCH_ALL_TAGS_ERROR = 'FETCH_ALL_TAGS_ERROR';
export const CREATE_NEW_TAG = 'CREATE_NEW_TAG';
export const CREATE_NEW_TAG_SUCCESS = 'CREATE_NEW_TAG_SUCCESS';
export const CREATE_NEW_TAG_ERROR = 'CREATE_NEW_TAG_ERROR';
