openapi: 3.0.0
info:
  title: Auth's API
  description: Authentication API
  version: 1.0.0
servers:
  - url: http://localhost:3001
    description: Local Dev
  - url: https://api-qa.semasoftware.com
    description: QA
  - url: https://api-staging.semasoftware.com
    description: staging
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Auth:
      properties:
        _id:
          type: string
        created:
          format: date-time
          type: string
        token:
          type: string
        userId:
          type: string
      required:
        - userId
        - token
      title: Auth
security:
  - bearerAuth: []
paths:
  /v1/auth/token:
    post:
      summary: create an auth token
      operationId: createAuthToken
      requestBody:
        content:
          application/json:
            schema:
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        200:
          content:
          description: create auth token
        400:
          description: bad input parameter
  /v1/auth/refresh-token:
    post:
      summary: create refresh token
      operationId: createRefreshToken
      responses:
        200:
          content:
          description: create auth token and refresh token renewed
        400:
          description: bad input parameter