openapi: 3.0.0
info:
  title: Support's API
  description: Email Support
  version: 1.0.0
servers:
  - url: http://localhost:3001
    description: Local Dev
  - url: https://api-qa.semasoftware.com
    description: QA
  - url: https://api-staging.semasoftware.com
    description: staging
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - bearerAuth: []
paths:
  /v1/support:
    post:
      summary: send email via sendgrid
      operationId: sendEmail
      requestBody:
        content:
          application/json:
            schema:
              properties:
                email:
                  type: string
                title:
                  type: string
                type:
                  type: string
                message:
                  type: string
      responses:
        200:
          content:
            application/json:
              schema:
                properties:
                  recipient:
                    type: string
                  templateName:
                    type: string
                  sender:
                    type: object
                  email:
                    type: string
                  title:
                    type: string
                  type:
                    type: string
                  message:
                    type: string
          description: email sent
        400:
          description: bad input parameter
  /v1/support/knowledgeBase:
    get:
      summary: fetch Sema's Knowledge Base articles.
      operationId: getKnowledgeBase
      parameters:
        - name: Authorization
          in: header
          description: Authorization Bearer type header with Intercom API key
          required: true
          type: string
      responses:
        200:
          content:
            application/json:
              schema:
                properties:
                  pages:
                    type: object
                  total_count:
                    type: integer
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        title:
                          type: string
                        description:
                          type: string
                        body:
                          type: string
                        parent_id:
                          type: integer
          description: Fetch Sema's Knowledge Base articles.
        401:
          description: Access Token Invalid