openapi: 3.0.0
info:
  title: Support's API
  description: Email Support
  version: 1.0.0
servers:
  - url: http://localhost:3001
    description: Local Dev
  - url: https://api-qa.semasoftware.com
    description: QA
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - bearerAuth: []
paths:
  /v1/support:
    post:
      summary: send email via sendgrid
      operationId: sendEmail
      requestBody:
        content:
          application/json:
            schema:
              properties:
                email:
                  type: string
                title:
                  type: string
                type:
                  type: string
                message:
                  type: string
      responses:
        200:
          content:
            application/json:
              schema:
                properties:
                  recipient:
                    type: string
                  templateName:
                    type: string
                  sender:
                    type: object
                  email:
                    type: string
                  title:
                    type: string
                  type:
                    type: string
                  message:
                    type: string
          description: email sent
        400:
          description: bad input parameter