export const FETCH_COLLECTION = 'FETCH_COLLECTION';
export const FETCH_COLLECTION_SUCCESS = 'FETCH_COLLECTION_SUCCESS';
export const FETCH_COLLECTION_ERROR = 'FETCH_COLLECTION_ERROR';
export const FETCH_SUGGESTED_COMMENTS = 'FETCH_SUGGESTED_COMMENTS';
export const FETCH_SUGGESTED_COMMENTS_SUCCESS = 'FETCH_SUGGESTED_COMMENTS_SUCCESS';
export const FETCH_SUGGESTED_COMMENTS_ERROR = 'FETCH_SUGGESTED_COMMENTS_ERROR';
