FROM public.ecr.aws/docker/library/node:16-alpine3.14 AS build

WORKDIR /usr/app
COPY ./.env ./.env
COPY ./package*.json ./

ENV NODE_ENV development
ENV PATH /usr/app/node_modules/.bin:$PATH
RUN npm install

CMD ["npm", "run", "worker"]
