openapi: 3.0.0
info:
  title: Search Queries' API
  description: Search Queries
  version: 1.0.0
servers:
  - url: http://localhost:3001
    description: Local Dev
  - url: https://api-qa.semasoftware.com
    description: QA
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - bearerAuth: []
paths:
  /v1/admin/search-queries:
    get:
      summary: get last queries
      operationId: getLastQueries
      parameters:
        - in: query
          name: page
          description: page number
          required: true
        - in: query
          name: perPage
          description: how many per page
          required: true
      responses:
        200:
          content:
            application/json:
              schema:
                properties:
                  queries:
                    type: array
                  totalCount:
                    type: number
          description: get queries
        400:
          description: bad input parameter
  /v1/admin/search-queries/export:
    post:
      summary: export search queries
      operationId: exportSearchQueries
      responses:
        200:
          description: exported search queries csv file
        400:
          description: bad input parameter