export const REQUEST_CREATE_REPO = 'REQUEST_CREATE_REPO';
export const REQUEST_CREATE_REPO_SUCCESS = 'REQUEST_CREATE_REPO_SUCCESS';
export const REQUEST_CREATE_REPO_ERROR = 'REQUEST_CREATE_REPO_ERROR';
export const REQUEST_FETCH_REPOS = 'REQUEST_FETCH_REPOS';
export const REQUEST_FETCH_REPOS_SUCCESS = 'REQUEST_FETCH_REPOS_SUCCESS';
export const REQUEST_FETCH_REPOS_ERROR = 'REQUEST_FETCH_REPOS_ERROR';
