openapi: 3.0.0
info:
  title: Github's Idendity API
  description: Github's Idendity
  version: 1.0.0
servers:
  - url: http://localhost:3001
    description: Local Dev
  - url: https://api-qa.semasoftware.com
    description: QA
  - url: https://api-staging.semasoftware.com
    description: staging
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Organization:
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        avatarUrl:
          type: string

    Repository:
      properties:
        repoId:
          type: string
        repoName:
          type: string
        description:
          type: string
        organizationId:
          type: string
        organizationName:
          type: string
        isPrivate:
          type: boolean

security:
  - bearerAuth: []
paths:
  /v1/identities/github:
    get:
      summary: get redirect uri
      parameters:
        - in: header
          name: x-forwarded-proto
          description: protocol
          required: true
        - in: header
          name: x-forwarded-host
          description: host
          required: true
      responses:
        200:
          description: redierct url
        400:
          description: bad input parameter
  /v1/identities/github/cb/{inviteToken}?:
    get:
      summary: get redirect uri
      parameters:
        - in: path
          name: inviteToken
          description: invite token
          required: true
      responses:
        200:
          description: redierct dashboard
        400:
          description: bad input parameter

  /v1/identities/github/organizations/{token}:
    get:
      summary: get organization list for the current authenticated user
      parameters:
        - in: path
          name: token
          description: github auth token or github access token
          required: true
        - in: query
          name: perPage
          description: count of records per page
          required: false
        - in: query
          name: page
          description: current page
          required: false
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Organization'
        400:
          description: bad input parameter

  /v1/identities/github/repositories/{token}:
    get:
      summary: get repositories list for the current authenticated user
      parameters:
        - in: path
          name: token
          description: github auth token or github access token
          required: true
        - in: query
          name: perPage
          description: count of records per page
          required: false
        - in: query
          name: page
          description: current page
          required: false
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Repository'
        400:
          description: bad input parameter

  /v1/identities/github/connect-orgs:
    post:
      summary: fetch and connect new orgs and repos for the logged user
      responses:
        200:
          content:
            application/json:
        400:
          description: bad input parameter
          content:
            application/json:
              schema:
                type: object
                properties:
                  reason:
                    type: string
                    description: Reason for next action
