export const FETCH_ALL_TEAMS = 'FETCH_ALL_TEAMS';
export const FETCH_ALL_TEAMS_SUCCESS = 'FETCH_ALL_TEAMS_SUCCESS';
export const FETCH_ALL_TEAMS_ERROR = 'FETCH_ALL_TEAMS_ERROR';
export const CREATE_NEW_TEAM = 'CREATE_NEW_TEAM';
export const CREATE_NEW_TEAM_SUCCESS = 'CREATE_NEW_TEAM_SUCCESS';
export const CREATE_NEW_TEAM_ERROR = 'CREATE_NEW_TEAM_ERROR';
