export const REQUEST_REPORT_URL = 'REQUEST_REPORT_URL';
export const RECEIVE_REPORT_URL = 'RECEIVE_REPORT_URL';
export const RECEIVE_REPORT_RUN_TOKEN = 'RECEIVE_REPORT_RUN_TOKEN';
export const REQUEST_REPORT_URL_ERROR = 'REQUEST_REPORT_URL_ERROR';
export const REQUEST_DOWNLOAD = 'REQUEST_DOWNLOAD';
export const REQUEST_DOWNLOAD_SUCCESS = 'REQUEST_DOWNLOAD_SUCCESS';
export const REQUEST_DOWNLOAD_ERROR = 'REQUEST_DOWNLOAD_ERROR';
