const phrases = [
  'array',
  'reference',
  'configuration',
  'library',
  'constructor',
  'database',
  'state',
  'performance',
  'algorithm',
  'validation',
  'interface',
  'properties',
  'complexity',
  'integer',
  'scope',
  'constants',
  'encryption',
  'binary',
  'random',
  'pointers',
  'bitwise',
  'authentication',
  'session',
  'stack',
  'optional',
  'enum',
  'file system',
  'template',
  'iteration',
  'macros',
  'assertions',
  'regex',
  'casting',
  'scheme',
  'synchronization',
  'search',
  'actor',
  'protocols',
  'logging',
  'stream',
  'floating point',
  'oracle',
  'wrapper',
  'embedded',
  'framework',
  'converting',
  'rest',
  'collections',
  'portability',
  'flask',
  'inheritance',
  'processing',
  'lambda',
  'socket',
  'cyclomatic complexity',
  'container',
  'closure',
  'formatting',
  'http',
  'layout',
  'javascript',
  'authorization',
  'namespaces',
  'python',
  'serialization',
  'collision',
  'reflection',
  'shell',
  'parsing',
  'recursion',
  'assembly',
  'locking',
  'interpreter',
  'escaping',
  'installer',
  'variadic',
  'helper',
  'image',
  'callback',
  'heap',
  'overloading',
  'optimization',
  'error handling',
  'compression',
  'join',
  'iterator',
  'lookup',
  'type safety',
  'atomic',
  'lazy',
  'asynchronous',
  'singleton',
  'user interface',
  'aes',
  'https',
  'proxy',
  'generics',
  'sql',
  'repository',
  'subroutine',
  'kernel',
  'smart pointers',
  'delegates',
  'extension methods',
  'exception handling',
  'timeout',
  'concurrency',
  'promise',
  'jwt',
  'backtracking',
  'constant expression',
  'object oriented',
  'virtual machine',
  'matrix',
  'hashcode',
  'machine learning',
  'dependency injection',
  'stored procedure',
  'mocks',
  'sqlalchemy',
  'pandas',
  'const',
  'struct',
  'exec',
  'expr',
  'condition',
  'lock',
  'argument',
  'exception',
  'throw',
  'private',
  'null',
  'character',
  'static',
  'actor',
  'signed',
  'loop',
  'deprecated',
  'arguments',
  'element',
  'factor',
  'import',
  'final',
  'literal',
  'pointer',
  'exit',
  'stream',
  'eval',
  'constructor',
  'boolean',
  'interface',
  'constant',
  'protected',
  'initialize',
  'catch',
  'password',
  'nested',
  'cast',
  'namespace',
  'literals',
  'override',
  'blob',
  'scope',
  'validate',
  'never executed',
  'public static',
  'throws',
  'enum',
  'encrypt',
  'arbitrary',
  'initialization',
  'throw new',
  'complexity',
  'directory',
  'critical',
  'compute',
  'neutralize',
  'insecure',
  'increment',
  'initialized',
  'identifiers',
  'sizeof',
  'primitive',
  'assert',
  'cryptographic',
  'constants',
  'escape',
  'guid',
  'map',
  'curl',
  'string literal',
  'const char',
  'stack',
  'protocol',
  'handler',
  'unsigned',
  'promise',
  'warning',
  'float',
  'nan',
  'printf',
  'permissions',
  'abstract',
  'encryption',
  'caught',
  'validated',
  'loops',
  'neutralizes',
  'compromise',
  'authentication',
  'release',
  'incorrectly neutralizes',
  'public function',
  'parentheses',
  'configuration file',
  'sql',
  'privileges',
  'unconditional',
  'special elements',
  'goto',
  'downstream component',
  'identity',
  'terminated',
  'response',
  'uint',
  'println',
  'code exec',
  'typedef',
  'regex',
  'weaknesses',
  'macros',
  'destructor',
  'inline',
  'law',
  'union',
  'null pointer',
  'join',
  'synchronize',
  'magic',
  'obsolete',
  'architecture',
  'large number',
  'certificate',
  'closure',
  'child class',
  'lambda',
  'prototype',
  'size_t',
  'trace',
  'const int',
  'parent class',
  'readonly',
  'async',
  'error message',
  'annotations',
  'regular expressions',
  'synchronized',
  'collections',
  'octal',
  'pathname',
  'locking',
  'tls',
  'environment variables',
  'block contain',
  'echo',
  'unique_ptr',
  'drop',
  'inheritance',
  'partial',
  'await',
  'amount',
  'exponent',
  'validates',
  'administrator',
  'unlock',
  'descriptor',
  'strategy',
  'strlen',
  'text block',
  'locked',
  'assembly',
  'floating point',
  'race condition',
  'callback',
  'incorrectly handles',
  'new object',
  'finalize',
  'mutex',
  'monitor',
  'deserialization',
  'file descriptor',
  'preprocessing',
  'delimiters',
  '__attribute__',
  'property name',
  'protection mechanism',
  'bit field',
  'params',
  'format string',
  'uint32_t',
  'random number',
  'unauthorized actor',
  'serializable',
  'typeof',
  'uint8_t',
  'pfile',
  'scan',
  'endpoint',
  'standard input',
  'certificates',
  'substring',
  'input validation',
  'lambdas',
  'transaction',
  'smaller functions',
  'sockets',
  'declarator',
  'import java',
  'closures',
  'delegate',
  'shared_ptr',
  'stores sensitive',
  'errno',
  'pragma',
  'dbo',
  'application stores',
  'security policy',
  'fname',
  'class implement',
  'noreturn',
  'magic numbers',
  'unreachable',
  'namespaces',
  'code dynamically',
  'style comments',
  'instanceof',
  'contain sensitive information',
  'string format',
  'application stores sensitive',
  'public override void',
  'certificate chain',
  'compound statement',
  'public const',
  'callable',
  'web browsers',
  'octal values',
  'concrete',
  'comma operator',
  'int16_t',
  'boolean equals',
  'mkstemp',
  'labeled',
  'int const',
  'user request',
  'command line',
  'md5',
  'hello world',
  'line arguments',
  'unsigned type',
  'singleton',
  'iterator',
  'public method',
  'stores sensitive information',
  'command line arguments',
  'working directory',
  'cleartext',
  'untrusted data',
  'subquery',
  'perform assignment',
  'key exchange',
  'public var',
  'async function',
  'subqueries',
  'chroot',
  'copyable',
  'using string',
  'signal handler',
  'data store',
  'trivially copyable',
  'smaller methods',
  '__construct',
  'application stores sensitive information',
  'block scope',
  'nonnull',
  'properly restrict',
  'outer class',
  'class contains',
  'code file',
  'multiple internal',
  'mixed content',
  'program violates',
  'typedefs',
  'iostream',
  'int field',
  'jdbc',
  'incorrectly validates',
  'public static int',
  'root_dir',
  'properly verify',
  'atoi',
  'int numbers',
  'xpath',
  'character class',
  'cstring',
  'subroutines',
  'varchar',
  'reserved words',
  'data members',
  'salt',
  'capitalization',
  'sprintf',
  'content security',
  'content security policy',
  'ldap',
  'special method',
  'coupled',
  'new int',
  'incorrectly restricts',
  'critical resource',
  'wchar_t',
  'scoped_lock',
  'configuring loggers',
  'fuses',
  'spoofed',
  'string password',
  'reentrant function',
  'untyped',
  'configuring',
  'member variables',
  'myclass',
  'validation form',
  'software defines',
  'virtual destructor',
  'reinterpret_cast',
  'encapsulated',
  'control element',
  'remote server',
  'exception handling',
  'first_name',
  'string_view',
  'constexpr int',
  'ctime',
  'explicit call',
  'fseek',
  'validation framework',
  'transmission',
  'always evaluate',
  'comparator',
  'used inside',
  'increment clause',
  'source code contains',
  'sequelize',
  'dynamic_cast',
  'mcrypt_encrypt',
  'int age',
  'ejb',
  'referer',
  'exceptional condition',
  'process object',
  'pragma warning',
  'call super',
  'comment syntax',
  'subprocedures',
  'matrix',
  'deserializing',
  'static_assert',
  'restricted use',
  'data manager',
  'package names',
  'incorrectly uses',
  'dynamic heap memory',
  'smaller subroutines',
  'heap memory',
  'cursor inside',
  'externally controlled',
  'executing code',
  'multiple trailing',
  'cloneable',
  'product exposes',
  'structured message',
  'assembly language',
  'snprintf',
  'const float',
  'specified size',
  'untrusted agents',
  'urllib',
  'external actors',
  'dynamic heap',
  'critical section',
  'keyword argument',
  'struts',
  'mockito',
  'principles',
  'desirable maximum',
  'properly protect',
  'across multiple',
  'serializable object',
  'validation logic',
  'package names match',
  'invalid_argument',
  'xss',
  'product calls',
  'output buffer',
  'parent element',
  'software validate',
  'offsetof',
  'operation codes',
  'zero initialization',
  'preprocessor operators',
  'metadata tag',
  'longjmp',
  'code sequence',
  'uses operator',
  'back reference',
  'flexible array',
  'variable type',
  'unions',
  'setuid',
  'plaintext password',
  'input validation framework',
  'pragma pack',
  'import static',
  'excessively large',
  'software stores sensitive information',
  'signed primitive',
  'debugging code',
  'software stores sensitive',
  'release function',
  'unsigned primitive',
  'parent classes',
  'implicitly inserted',
  'uses multiple',
  'web browsers perform',
  'relatively small',
  'virtual method',
  'contains data',
  'browsers perform',
  'branching',
  'private variable',
  'particular element',
  'data access',
  'dynamic clauses',
  'end condition',
  'explicitly authorized',
  'synchronized block',
  'int glob',
  'interceptors',
  'fetch directives',
  'public object',
  'int matrix',
  'another actor',
  'end exec',
  'program calls',
  'respect user',
  'exposes sensitive',
  'completely specified',
  'reveal sensitive',
  'unnecessarily large',
  'cloned mutable',
  'cloned mutable data',
  'mutable data',
  'unnecessarily large number',
  'session id',
  'expanding archive files',
  'exposes security',
  'expanding archive',
  'hashlib',
  'quantitative',
  'program less',
  'override public function',
  'persistent cookies',
  'const long',
  'insecure permissions',
  'intended buffer',
  'program less readable',
  'internal variable',
  'equal objects',
  'specific error',
  'multiple leading',
  'protected string',
  'spatula',
  'incorrect usage',
  'uname',
  'trailing slash',
  'strawberry',
  'hidden files',
  'reference count',
  'revocation',
  'corresponding validation',
  'structural element',
  'unintended results',
  'software component',
  'runnable',
  'class loader',
  'serialization method',
  'drop privileges',
  'interceptor',
  'restricts access',
  'serializable data',
  'restrict reading',
  'comparison function',
  'junit5',
  'python class',
  'wrong ownership',
  'separate standalone',
  'authentication technique',
  'isolate system',
  'separate standalone modules',
  'standalone modules',
  'pipelined',
  'new environment',
  'neutralizes output',
  'directories accessible',
  'incorrectly neutralizes output',
  'throwable',
  'default error page',
  'display sensitive',
  'display sensitive information',
  'generic exceptions',
  'compliant comment',
  'maintain equal hashcodes',
  'inappropriately exposed',
  'potentially sensitive',
  'potentially sensitive information',
  'yielding potentially sensitive',
  'yielding potentially sensitive information',
  'complexity measure exceeds',
  'functionality changes',
  'thread synchronization primitives',
  'using thread synchronization',
  'using thread synchronization primitives',
  'incorrect group',
  'code contains callable',
  'exception handling block',
  'software locks',
  'invokable code',
  'invokable code block',
  'deserialization configuration',
  'trailing whitespaces',
  'static code block',
  'accidental addition',
  'requires authentication',
  'require authentication',
  'return custom error pages',
  'return custom error',
  'possibly exposing sensitive information',
  'possibly exposing sensitive',
  'empty synchronized',
  'using framework method',
  'uses sockets instead',
  'framework method calls',
  'directly accesses',
  'framework method',
  'directly uses sockets',
  'insecure behavior',
  'nullable value',
  'incorrectly neutralizes delimiters',
  'declare total',
  'hooray',
  'less secure value',
  'uncaught_exceptions',
  'accidental deletion',
  'logic error',
  'neutralizes delimiters',
  'makes program',
  'initialize critical',
  'mainline procedure',
  'hardcoding',
  'phpunit',
  'factor authentication',
  'hashcodes',
  'correctly manage seeds',
  'actor without verifying',
  'software unlocks',
  'unconditional branches',
  'messages help attackers learn',
  'initialize critical variables',
  'software contains dead code',
  'contains dead code',
  'correctly convert',
  'wrong handler',
  'one concrete',
  'maintain reference',
  'properly handle input',
  'smaller procedures',
  'block empty',
  'uses persistent cookies',
  'cookies contain sensitive information',
  'reads data past',
  'variables may contain sensitive',
  'may contain sensitive information',
  'may contain sensitive',
  'incorrect argument',
  'associated serialization',
  'associated copy',
  'associated serialization method',
  'software writes data past',
  'immutable identifiers',
  'multiple trailing slash',
  'insufficient session',
  'inconsistent implementations across operating',
  'backticks',
  'debug interface',
  'multiple leading slash',
  'connection creation',
  'sufficiently restrict',
  'incorrectly restricts access',
  'properly maintain reference',
  'incorrectly releases',
  'generates numbers',
  'properly clean',
  'cross join',
  'remove temporary',
  'properly isolate shared resources',
  'mutate',
  'immutable element',
  'across multiple architectural',
  'associated virtual destructor',
  'across multiple architectural layers',
  'sensitive values',
  'multiple architectural layers',
  'control element across multiple',
  'architectural layers',
  'smaller sections',
  'smaller paragraphs',
  'teardown',
  'duplicate key',
  'secure design',
  'path equivalence',
  'prevents dangerous',
  'overly restrictive',
  'dangerous values',
  'may reveal sensitive',
  'sensitive debugging information',
  'implementations across operating systems',
  'callables',
  'concrete class',
  'system compromise',
  'sensitive hardware module',
  'performing sensitive operations',
  'cryptographic signature',
  'incorrectly verifies',
  'encrypt sensitive',
  'plaintext may',
  'established principles',
  'singleton pattern',
  'multithreaded environment',
  'incomplete functionality',
  'software interfaces',
  'adequately define inputs',
  'lookahead',
  'equal hashcodes',
  'company policy',
  'empty lines',
  'server error message',
  'network failure',
  'transmitting sensitive',
  'exposes sensitive information',
  'transmitting sensitive data',
  'unique identifiers',
  'product violates',
  'wrong action',
  'element selectors',
  'conditional logic',
  'unused validation',
  'unused validation form',
  'signal handlers',
  'immutable text string',
  'concatenation operations',
  'causes incorrect logic',
  'published specifications',
  'incorrect logic',
  'precedence causes incorrect logic',
  'operator precedence causes incorrect',
];
export default phrases;
