const phrases = [
  'AWT Swing',
  'Absolute Path Traversal',
  'Absolute Position',
  'Acceptance',
  'Access Child',
  'Access Control List Files to',
  'Accessible File',
  'Active Allocated Resource',
  'Active Debug Code',
  'Active File Descriptor',
  'Add spaces inside curly braces',
  'Addition',
  'Additional Special Element',
  'Administrative functions',
  'Alignment',
  'Alist',
  'Allowed Inputs',
  'Alt prop',
  'Alternate Encoding',
  'Alternate Name',
  'Alternate XSS Syntax',
  'Always False',
  'Always True',
  'Always put default parameters last',
  'Always use JSX syntax',
  'Always use class',
  'Always use const',
  'Always use modules',
  'Angus Croll',
  'Another Class',
  'Another Sphere',
  'Apple HFS',
  'Architecture',
  'Are',
  'Argument Delimiters',
  'Argument Injection',
  'Array Declared Public, Final,',
  'Array Destructuring',
  'Array Index',
  'Arrow functions',
  'Assigning instead',
  'Asymmetric Resource Consumption',
  'Attributes',
  'Audit Tracking',
  'Authentication Bypass Using',
  'Authorization levels',
  'Avoid double negative logic',
  'Avoid duplicate class members',
  'Avoid linebreaks',
  'Avoid multiple empty lines',
  'Avoid side effects',
  'Avoid trailing spaces',
  'Avoid unneeded ternary statements',
  'Awesome',
  'Awesome job meeting functional requirements',
  'Backup File to',
  'Basic XSS',
  'Behaving Entities',
  'Behavioral Workflow',
  'Block vs',
  'Boot Phase',
  'Bounds',
  'Broadcast Receiver',
  'Buffer Over',
  'Buffer Size',
  'Buffer Under',
  'Buffer Underflow',
  'Business Rules',
  'Byte String Length',
  'CBC Mode',
  'CRLF Injection',
  'CSRF',
  'Cache Containing Sensitive Information',
  'Callable',
  'Canonical URL Paths',
  'Canonicalization',
  'Case Sensitivity',
  'Cast',
  'Catch',
  'Certificate Expiration',
  'Certificate Revocation',
  'Certification Requirements',
  'Channel Accessible',
  'Checked Locking',
  'Chicken Bits',
  'Child Class',
  'Child Classes',
  'Circular Dependencies',
  'Class Instance Self Destruction Control Element',
  'Class Loader',
  'Class methods',
  'Class vs React',
  'Classes',
  'Classic Buffer Overflow',
  'Clear Buffers',
  'Cleartext Storage',
  'Cleartext Transmission',
  'Clever',
  'Clock Glitches',
  'Cloneable Class Containing Sensitive Information',
  'Code Injection',
  'Coded Literals',
  'Coded Network Resource Configuration Data',
  'Coding Standards',
  'Collapse',
  'Command Delimiters',
  'Command Shell',
  'Comment Delimiters',
  'Comparing instead',
  'Comparison Using Wrong Factors',
  'Competence',
  'Compilation',
  'Compiler Optimization Removal',
  'Component naming',
  'Compute properties when possible',
  'Concrete Classes',
  'Conditional statements',
  'Configuration File',
  'Configuration Setting',
  'Connection Pooling',
  'Connections',
  'Context Switching Race Condition',
  'Control Repository to',
  'Controlled Format String',
  'Controlled Key',
  'Controlled SQL Primary Key',
  'Cookies without Validation',
  'Core Dump File to',
  'Correct Object',
  'Covert Channel',
  'Covert Storage Channel',
  'Covert Timing Channel',
  'Created',
  'Creating Debug Binary',
  'Critical Action',
  'Critical Data Element Declared Public',
  'Critical Function',
  'Critical Private Variable via Public Method',
  'Critical Public Variable Without Final Modifier',
  'Critical State Data',
  'Cryptographic Signature',
  'Cryptographically Weak Pseudo',
  'Cursor Injection',
  'Custom URL Scheme',
  'DATA Alternate Data Stream',
  'DTDs',
  'Dangerous Operations',
  'Dangerous Signal Handler not Disabled During Sensitive Operations',
  'Dangerous Type',
  'Data Access Operations Outside',
  'Data Amplification',
  'Data Authenticity',
  'Data Element containing Pointer Item without Proper Copy Control Element',
  'Data Query Logic',
  'Data Resource Accesses',
  'Data Stores',
  'Data Transmission Without Encryption',
  'Data within XPath Expressions',
  'Dead Code',
  'Deadlock',
  'Declaration',
  'Defined Behavior',
  'Deletion',
  'Delimiters',
  'Dependent Data Representation',
  'Dependent Functionality',
  'Dependent Functions',
  'Dependent Third Party Components',
  'Deployment',
  'Deserialization',
  'Determine Size',
  'Determined Object Attributes',
  'Direct Request',
  'Disable Reserved Bits',
  'Disallow unused variables',
  'Divide By Zero',
  'Do not add spaces inside brackets',
  'Do not add spaces inside parentheses',
  'Do not export directly from',
  'Do not export mutable bindings',
  'Do not pad',
  'Do not use mixins',
  'Do not use multiple blank lines',
  'Do not use wildcard imports',
  'Document Type Definition',
  'Documented Design',
  'Don’t chain variable assignments',
  'Don’t use generators',
  'Double Free',
  'Doubled Character XSS Manipulations',
  'Download',
  'Dropped Privileges',
  'Duplicate Operations',
  'Duplicate Validation Forms',
  'Dynamic Variable Evaluation',
  'EAR',
  'ECMA',
  'EJB Methods',
  'Early Amplification',
  'Early Validation',
  'Economy',
  'Embedded Malicious Code',
  'Emergent Resource',
  'Empty Code Block',
  'Empty Exception Block',
  'Empty Password',
  'Empty Synchronized Block',
  'Encoded URI Schemes',
  'Encoding Error',
  'End files',
  'Enforce coding rules autoamtically',
  'Enforce spacing inside',
  'Entity Bean Declared Remote',
  'Equals',
  'Equivalent Special Elements',
  'Error Condition Without Action',
  'Error Handling Techniques',
  'Error Message Web Page',
  'Escape, Meta,',
  'Escaping',
  'Eval Injection',
  'Event handlers',
  'Excellence',
  'Exceptional Conditions',
  'Excessive Attack Surface',
  'Excessive Authentication Attempts',
  'Excessive Code Complexity',
  'Excessive Execution',
  'Excessive File',
  'Excessive Halstead Complexity',
  'Excessive Iteration',
  'Excessive McCabe Cyclomatic Complexity',
  'Excessive Platform Resource Consumption within',
  'Excessively Complex Data Representation',
  'Excessively Deep Inheritance',
  'Excessively Deep Nesting',
  'Executable',
  'Executable Regular Expression Error',
  'Execute Operations',
  'Expected Behavior Violation',
  'Expected Conventions',
  'Expiration',
  'Expired File Descriptor',
  'Expired Pointer Dereference',
  'Exposed Chip Debug Interface With Insufficient Access Control',
  'Exposed Dangerous Method',
  'Exposed IOCTL',
  'Exposed Unsafe ActiveX Method',
  'Expression Language Injection',
  'Extension naming',
  'External Interfaces',
  'External Parties',
  'Extra Parameters',
  'Extra Values',
  'FSMs',
  'Failed Initialization',
  'Failing Open',
  'File Descriptor Leak',
  'File Descriptors',
  'File Name',
  'File Names',
  'File With Sensitive Data Under FTP Root',
  'File naming',
  'Finalize',
  'Flag',
  'Floating Point Comparison',
  'Follow consistent definitions',
  'Forgotten Password',
  'Form Bean Does Not Extend Validation Class',
  'Form Field Without Validator',
  'Formatting',
  'Frames',
  'Function Call With Incorrect Argument Type',
  'Function Call With Incorrect Number',
  'Function Call With Incorrect Order',
  'Function Call With Incorrect Variable',
  'Function Call With Incorrectly Specified Argument Value',
  'Function Hook Arguments',
  'Function declarations hoist',
  'Functional requirements not met',
  'Future coders',
  'GET Request Method With Sensitive Query Strings',
  'GUI',
  'Generated Code',
  'Generated Error Message Containing Sensitive Information',
  'Generation',
  'Generator function signature spacing',
  'Generators',
  'Genius',
  'Global Variables',
  'Growth',
  'Guessable CAPTCHA',
  'HTTP Requests',
  'HTTP Response Splitting',
  'HTTPS Session Without',
  'Handle Incomplete Element',
  'Handle Missing Parameter',
  'Hardware Internal',
  'Hardware Register',
  'Have',
  'Heap Inspection',
  'Help',
  'Hex Encoding',
  'Hibernate',
  'Hidden Functionality',
  'Higher',
  'Historical Data',
  'Homoglyphs Presented',
  'Host Mismatch',
  'I can',
  'I don',
  'I find',
  'I know Kung Fu',
  'I,',
  'ID Length',
  'IMG Tags',
  'IP Address',
  'Identified Variables',
  'Identity Impersonation',
  'If',
  'Immutable Data',
  'Immutable Text Using String Concatenation',
  'Immutable Web Parameter',
  'Impersonation',
  'Implicit Intent',
  'Improper Access Control',
  'Improper Authentication',
  'Improper Authorization',
  'Improper Certificate Validation',
  'Improper Cleanup',
  'Improper Export',
  'Improper Filtering',
  'Improper Implementation',
  'Improper Initialization',
  'Improper Input Validation',
  'Improper Link Resolution Before File Access',
  'Improper Lock Behavior After Power State Transition',
  'Improper Locking',
  'Improper Model Validation',
  'Improper Neutralization',
  'Improper Null Termination',
  'Improper Ownership Management',
  'Improper Preservation',
  'Improper Privilege Management',
  'Improper Protection',
  'Improper Removal',
  'Improper Resolution',
  'Improper Resource Locking',
  'Improper Resource Shutdown',
  'Improper Synchronization',
  'Improper Update',
  'Improper Use',
  'Improper Verification',
  'Improperly Implemented Security Check',
  'Improve',
  'Inaccurate Comments',
  'Inadequate Detection',
  'Inadequate Encryption Strength',
  'Inappropriate Comment Style',
  'Inappropriate Whitespace Style',
  'Include File',
  'Incompatible Policies',
  'Incompatible Types',
  'Incomplete Cleanup',
  'Incomplete Design Documentation',
  'Incomplete Documentation',
  'Incomplete Filtering',
  'Incomplete Internal State Distinction',
  'Incomplete List',
  'Incomplete Model',
  'Incomplete Structural Elements',
  'Inconsistent Implementations',
  'Inconsistent Naming Conventions',
  'Inconsistent Special Elements',
  'Inconsistent Structural Elements',
  'Incorrect Authorization',
  'Incorrect Behavior Order',
  'Incorrect Block Delimitation',
  'Incorrect Byte Ordering',
  'Incorrect Calculation',
  'Incorrect Check',
  'Incorrect Comparison',
  'Incorrect Control Flow Implementation',
  'Incorrect Control Flow Scoping',
  'Incorrect Default Permissions',
  'Incorrect Execution',
  'Incorrect Implementation',
  'Incorrect Length Value',
  'Incorrect Operator',
  'Incorrect Ownership Assignment',
  'Incorrect Permission Assignment',
  'Incorrect Pointer Scaling',
  'Incorrect Privilege Assignment',
  'Incorrect Provision',
  'Incorrect Regular Expression',
  'Incorrect Resource Transfer Between Spheres',
  'Incorrect Short Circuit Evaluation',
  'Incorrect Synchronization',
  'Incorrect User Management',
  'Incorrectly Specified Arguments',
  'Incorrectly Specified Destination',
  'Index Containing Sensitive Information',
  'Indexes',
  'Indices',
  'Inefficient Algorithmic Complexity',
  'Inefficient CPU Computation',
  'Inefficient Server',
  'Infinite Loop',
  'Information Loss',
  'Information Through Directory Listing',
  'Information Through Shell Error Message',
  'Inherently Dangerous Function',
  'Inner Class Containing Sensitive Data',
  'Input Leaders',
  'Input Terminators',
  'Insecure Automated Optimizations',
  'Insecure Default Initialization',
  'Insecure Default Variable Initialization',
  'Insecure Inherited Permissions',
  'Insecure Permissions',
  'Insecure Preserved Inherited Permissions',
  'Insecure Storage',
  'Insecure Temporary File',
  'Insufficient Compartmentalization',
  'Insufficient Control Flow Management',
  'Insufficient Encapsulation',
  'Insufficient Entropy',
  'Insufficient Granularity',
  'Insufficient Logging',
  'Insufficient Permissions',
  'Insufficient Privileges',
  'Insufficient Psychological Acceptability',
  'Insufficient Resource Pool',
  'Insufficient Session Expiration',
  'Insufficient Type Distinction',
  'Insufficient Use',
  'Insufficiently Protected Credentials',
  'Insufficiently Random Values',
  'Integer Coercion Error',
  'Integer Overflow',
  'Integer Underflow',
  'Integrity Check Value',
  'Intended Endpoints',
  'Interaction Frequency',
  'Intermediary',
  'Internal Dot',
  'Internal Special Elements',
  'Interpretation Conflict',
  'Invalid Pointer',
  'Invalid Use',
  'Invariant Value',
  'Irrelevant Code',
  'J2EE Bad Practices',
  'J2EE Framework',
  'JSX curly braces',
  'Java I',
  'Java Runtime Error Message Containing Sensitive Information',
  'Just keep swimming',
  'Kat says Yay!',
  'Key Exchange without Entity Authentication',
  'LDAP Query',
  'LNK',
  'Lack',
  'Leading Space',
  'Leading Special Elements',
  'Least Privilege Violation',
  'Leave',
  'Legal',
  'Length Parameter Inconsistency',
  'Less Trusted Source',
  'Level Admin Tool',
  'Level Functionality',
  'Limited',
  'Line Delimiters',
  'Lines',
  'Log File',
  'Logging',
  'Logs',
  'Long Expiration',
  'Loop Condition Value Update within',
  'Lowering Errors',
  'MAID',
  'Macro Symbols',
  'Make',
  'Managed Code Resources',
  'May',
  'Meets functional requirements',
  'Memory Layout',
  'Memory Location After End',
  'Memory Location Before Start',
  'Message Integrity During Transmission',
  'Method Declared Public',
  'Method Definition',
  'Mirrored Regions',
  'Misinterpretation',
  'Mismatched Memory Management Routines',
  'Missing Authorization',
  'Missing Check',
  'Missing Critical Step',
  'Missing Custom Error Page',
  'Missing Documentation',
  'Missing Encryption',
  'Missing Factors',
  'Missing Handler',
  'Missing Initialization',
  'Missing Lock Check',
  'Missing Password Field Masking',
  'Missing Release',
  'Missing Report',
  'Missing Required Cryptographic Step',
  'Missing Serialization Control Element',
  'Missing Special Element',
  'Missing Standardized Error Handling Mechanism',
  'Missing Support',
  'Missing Synchronization',
  'Missing Validation',
  'Missing Values',
  'Missing XML Validation',
  'Mixed Encoding',
  'Modifying Code',
  'Module Parameters',
  'More Instances',
  'Multiline imports intendenting',
  'Multiple Architectural Layers',
  'Multiple Dot',
  'Multiple Instances',
  'Multiple Internal Dot',
  'Multiple Internal Special Elements',
  'Multiple Leading Special Elements',
  'Multiple Locks',
  'Multiple Resources',
  'Multiple Signals',
  'Multiple Trailing Dot',
  'Multiple Trailing Special Elements',
  'Multiple Unlocks',
  'Multuple Return Value Destructuring',
  'NUL Character',
  'NULL Pointer Dereference',
  'Network Amplification',
  'Never mutate parameters',
  'Never name',
  'Never reassign parameters',
  'Never tell',
  'Never use arguments',
  'New Version',
  'Not Using Complete Mediation',
  'Not Using Input Validation Framework',
  'Not Using Password Aging',
  'NullPointerException Catch',
  'Numeric Range Comparison Without Minimum Check',
  'Numeric Truncation Error',
  'Numeric Types',
  'O Control Code',
  'O Documentation',
  'OS Command',
  'Obfuscation',
  'Object Contents',
  'Object Destructuring',
  'Object Hijack',
  'Object without Invoking Destructor Method',
  'Obscured Security',
  'Observable Behavioral Discrepancy',
  'Observable Behavioral Discrepancy With Equivalent Products',
  'Observable Discrepancy',
  'Observable Internal Behavioral Discrepancy',
  'Observable Response Discrepancy',
  'Observable State',
  'Observable Timing Discrepancy',
  'Obsolete Feature',
  'Obsolete Function',
  'Omission',
  'Omit value',
  'Omitted Break Statement',
  'Once Attributes',
  'Once Bit Fields',
  'One React component per file',
  'Open Redirect',
  'Open–closed principle',
  'Operator Precedence Logic Error',
  'Origin Validation Error',
  'Other Resources',
  'Output Context',
  'Output Used',
  'Outside Expected Data Manager Component',
  'Outward Calls',
  'Overly Restrictive Account Lockout Mechanism',
  'Overly Restrictive Regular Expression',
  'Ownership',
  'PHP External Variable Modification',
  'PHP Program',
  'Package',
  'Parameters',
  'Parent Class without Virtual Destructor Method',
  'Parentheses',
  'Partial String Comparison',
  'Password Hash Instead',
  'Password Hash With Insufficient Computational Effort',
  'Password System',
  'Path Traversal',
  'Permission Race Condition During Resource Copy',
  'Permissive Regular Expression',
  'Persistent Cookies Containing Sensitive Information',
  'Persistent Storable Data Element without Associated Comparison Control Element',
  'Physical Debug',
  'Placement',
  'Plaintext Password',
  'Plug',
  'Pointer Value Outside',
  'Pointer not',
  'Poison Null Byte',
  'Potentially Dangerous Function',
  'Power Consumption',
  'Predictable Algorithm',
  'Predictable Exact Value',
  'Predictable Numbers',
  'Predictable Seed',
  'Predictable Value Range',
  'Prefer',
  'Prefixing',
  'Premature Release',
  'Primary Weakness',
  'Primitive Elements',
  'Private Data Structure Returned From A Public Method',
  'Private Personal Information to',
  'Privilege Chaining',
  'Privilege Context Switching Error',
  'Privilege Defined With Unsafe Actions',
  'Privileged APIs',
  'Process Control',
  'Process Using Visible Sensitive Information',
  'Processor Optimization Removal',
  'Product UI does not Warn User',
  'Program Execution',
  'Prohibited Code',
  'Props naming',
  'Protection Mechanism Failure',
  'Public Static Field Not Marked Final',
  'Public Static Final Field References Mutable Object',
  'Put',
  'Qui',
  'Quotes',
  'Quoting Syntax',
  'RSA Algorithm without OAEP',
  'Race Condition During Access',
  'Race Condition Enabling Link Following',
  'Race Condition within',
  'Range Error',
  'Reachable Assertion',
  'Reassign',
  'Record Delimiters',
  'Reduce',
  'Redundant Code',
  'Reference naming',
  'References',
  'Reflection Attack in',
  'Refs',
  'Register Locks',
  'Regular Expression without Anchors',
  'Relative Path Traversal',
  'Replicating Malicious Code',
  'Reporting Requirements',
  'Resolved Name',
  'Resource Injection',
  'Resources Without Limits',
  'Responsibility Principle',
  'Return Inside Finally Block',
  'Returning',
  'Reuse',
  'Reusing',
  'Reversible One',
  'SQL Command',
  'SSI',
  'SSRF',
  'Same Port',
  'Same Seed',
  'Same Variable',
  'Sanitize Paired Delimiters',
  'Say hello to',
  'Scrappiness',
  'Scripting Syntax',
  'Section Delimiters',
  'Secure Design Principles',
  'Security Sensitive Controls',
  'Security Through Obscurity',
  'Seeds',
  'Select Classes',
  'Selection',
  'Semiconductor Defects',
  'Sensitive Data Storage',
  'Sensitive Data Under Web Root',
  'Sensitive Fuse Values During Debug',
  'Sensitive Information Into Debugging Code',
  'Sensitive Information Through Data Queries',
  'Sensitive Information Through Environmental Variables',
  'Sensitive Information Through Metadata',
  'Sensitive Information Through Sent Data',
  'Sensitive Information to',
  'Sensitive System Information to',
  'Serializable Class Containing Sensitive Data',
  'Serializable Item Elements',
  'Servlet',
  'Servlet Runtime Error Message Containing Sensitive Information',
  'Session Fixation',
  'Set off operators',
  'Shared Data',
  'Shared Resources',
  'Shared State',
  'Shatter',
  'Show',
  'Side Authentication',
  'Side Security',
  'Signal Handler Race Condition',
  'Signal Handler Use',
  'Signature Containing',
  'Signed Conversion Error',
  'Single Dot Directory',
  'Singleton Class Instance Creation without Proper Locking',
  'Singleton Pattern Without Synchronization',
  'Site Scripting',
  'Small Seed Space',
  'Small Space',
  'Sockets',
  'Source Buffer',
  'Source Code',
  'Source Code Comments',
  'Source Code Element without Standard Prologue',
  'Spacing',
  'Special Elements',
  'Specification',
  'Sphere Definition',
  'Spoofing',
  'Spread props',
  'Spyware',
  'Stack',
  'Stack Variable Address',
  'Static Code Block',
  'Static Code Injection',
  'Storing Passwords',
  'Structural Elements',
  'Substitution Characters',
  'Super apprecative',
  'Supplied File',
  'Suspicious Comment',
  'Switch',
  'Switch Block',
  'Switch Statement',
  'Symbolic Constant Definitions',
  'Symlink',
  'Synchronization Primitives',
  'Synchronous Access',
  'Syntactically Invalid Structure',
  'System Event Data',
  'TOCTOU',
  'TRNG',
  'Tell',
  'Temporary File With Insecure Permissions',
  'Test Code',
  'That is',
  'Thens',
  'There',
  'This works',
  'Thread Context',
  'Thread run',
  'Threads',
  'Throws',
  'Time Bomb',
  'Trailing Backslash',
  'Trailing Dot',
  'Trailing Slash',
  'Trailing Space',
  'Trailing Special Elements',
  'Trapdoor',
  'Triple Dot',
  'Trojan Horse',
  'Truncation',
  'Trust Boundary Violation',
  'Type Confusion',
  'Typed Field',
  'Types',
  'UI Discrepancy',
  'UI Input',
  'UNCsharename',
  'UNIX Hard Link',
  'Ugh I know',
  'Unboxing',
  'Uncaught Exception',
  'Unchecked Error Condition',
  'Unchecked Input',
  'Unchecked Return Value',
  'Unconditional Branching',
  'Uncontrolled Memory Allocation',
  'Uncontrolled Recursion',
  'Uncontrolled Resource Consumption',
  'Uncontrolled Search Path Element',
  'Undefined Behavior',
  'Undefined Parameters',
  'Undefined Values',
  'Unexpected Data Type',
  'Unexpected Sign Extension',
  'Unexpected Status Code',
  'Unicode Encoding',
  'Unimplemented',
  'Uninitialized Pointer',
  'Uninitialized Resource',
  'Uninitialized Variable',
  'Unmaintained Third Party Components',
  'Unnecessarily Wide Scope',
  'Unnecessary Privileges',
  'Unparsed Raw Web Content Delivery',
  'Unprotected Alternate Channel',
  'Unprotected Primary Channel',
  'Unprotected Storage',
  'Unprotected Transport',
  'Unquoted Search Path',
  'Unrestricted Externally Accessible Lock',
  'Unsafe ActiveX Control Marked Safe For Scripting',
  'Unsafe JNI',
  'Unsigned Conversion Error',
  'Untrusted Control Sphere',
  'Untrusted Execution Core Before Enabling Fabric Access Control',
  'Untrusted Inputs',
  'Untrusted Method',
  'Untrusted Pointer Dereference',
  'Untrusted Search Path',
  'Untrusted Source',
  'Unused Validation Form',
  'Unusual',
  'Unvalidated Action Form',
  'Unverified Ownership',
  'Unverified Password Change',
  'Uploaded File Variables',
  'Use After Free',
  'Use braces with',
  'Use dot notation when accessing properties',
  'Use exponentiation operator ** when calculating exponentiations',
  'Use indentation when making long method chains',
  'Use one const',
  'User Experience',
  'User Interface',
  'Using Components without Unique, Immutable Identifiers',
  'Using Referer Field',
  'Validate Before Canonicalize',
  'Validate Before Filter',
  'Validator Turned Off',
  'Validator Without Form Field',
  'Value Delimiters',
  'Values',
  'Variable Extraction Error',
  'Variable Name Delimiters',
  'Variable without Use',
  'Variadic Parameters',
  'Virtual Method without',
  'WSDL File Containing Sensitive Information',
  'Way Hash without',
  'We solve',
  'Weak Encoding',
  'Weak Password Requirements',
  'Web Browser Cache Containing Sensitive Information',
  'Web Link',
  'Web Pages',
  'When mixing operators, enclose them',
  'Whitespace',
  'Why so serious?',
  'Wildcards',
  'Windows 8',
  'Windows Device Names',
  'Windows Hard Link',
  'Worm',
  'Wow',
  'Wraparound',
  'Wrong Action',
  'Wrong Operator',
  'Wrong Phase',
  'Wrong Session',
  'Wrong Sphere',
  'Wrong Status Code',
  'XML External Entity Reference',
  'XML Injection',
  'XQuery Injection',
  'You Don',
  'You worked hard',
  'a Broken',
  'a CSV File',
  'a Child Class without',
  'a Command',
  'a Component Built',
  'a Concurrent Context',
  'a Control Element at',
  'a Cookie',
  'a Data Resource',
  'a Different Plane',
  'a File or',
  'a Fixed Address',
  'a Key Past its Expiration Date',
  'a Large Data Table',
  'a Marker',
  'a Mechanism without Access Control',
  'a New Sphere',
  'a Pathname',
  'a Predictable Salt',
  'a Resource Through its Lifetime',
  'a Risky Cryptographic Primitive',
  'a Single Factor',
  'a Single, Unique Action',
  'a Singleton Class Element',
  'a Special Element',
  'a Specified Location',
  'a Variable',
  'a box',
  'a lid',
  'a path',
  'a pile',
  'a space',
  'a variable',
  'absolute',
  'absolutepathnamehere',
  'advice',
  'alt props',
  'always include parentheses around arguments',
  'amend',
  'annotate problems',
  'annotate solutions',
  'arm',
  'around Error',
  'based Buffer Overflow',
  'bed,',
  'big difference',
  'bounds Read',
  'bounds Write',
  'camelCase',
  'cancellations',
  'case',
  'choice there',
  'chroot Jail Without Changing Working Directory',
  'class extends',
  'clone',
  'close tags',
  'close to',
  'closing tag',
  'coded Credentials',
  'coded Cryptographic Key',
  'coded Password',
  'coded, Security',
  'commas',
  'comparison operators',
  'convert',
  'copy',
  'createClass',
  'createElement',
  'creation',
  'custom toString',
  'debug',
  'decrements',
  'default constructor',
  'define explicit defaultProps',
  'different component here',
  'different framework here',
  'different method here',
  'different style',
  'dirname',
  'domain Whitelist',
  'dynamic property names',
  'elements',
  'else',
  'eqeqeq',
  'extensions',
  'factor Authentication',
  'fakedir',
  'far',
  'file name',
  'filedir',
  'filedir*',
  'filename',
  'finalize',
  'fix this',
  'fixed',
  'forbid',
  'function assignment',
  'function block',
  'function name',
  'generated Error Message Containing Sensitive Information',
  'getlogin',
  'group shorthand properties',
  'him',
  'huge fan',
  'implicit',
  'indented',
  'inheritance',
  'internal',
  'internal methods',
  'isMounted',
  'key prop',
  'keyword spacing',
  'knowing',
  'lace 1 space',
  'laws',
  'leading',
  'lgtm Looks good',
  'line components',
  'literal syntax',
  'll reuse',
  'll use',
  'longer',
  'm just',
  'm proud',
  'made',
  'mapping overable iterables',
  'me?',
  'method chaining',
  'module import statements',
  'multiline',
  'multipleinternalbackslash',
  'multuple lines',
  'mutating function arguments',
  'named export',
  'nested',
  'new function',
  'new lines',
  'no wish',
  'not Asynchronous',
  'not Locked',
  'not call Object',
  'not use eval',
  'object method shorthand',
  'omit',
  'one Error',
  'ooh,',
  'our enemy',
  'out Code',
  'parantheses',
  'positive',
  'private Field',
  'property value shorthand',
  'quote properties',
  'range Pointer Offset',
  're home',
  're human',
  'render methods',
  'replay',
  's Chain',
  's Unpossible',
  's alive!',
  's coming',
  's just',
  'sense',
  'serializable Object Stored',
  'set',
  'shallow',
  'show',
  'single line',
  'site Scripting',
  'sized Buffer',
  'sizeof',
  'sleep',
  'so happy',
  'so psyched',
  'sort',
  'started',
  'strings',
  't use selection operators',
  'templates',
  'the Heap',
  'the Registry',
  'the Same Data',
  'the Server Side',
  'the framework',
  'the next token',
  'their invocations',
  'thought',
  'tip!',
  'to convert',
  'told',
  'top',
  'trailing',
  'truth',
  'ubiquitous API',
  'umask',
  'use arrow function notationfor anonymous function',
  'use escape characters sparingly',
  'use instead',
  'use line breaks',
  'use nameed function expressions',
  'use push',
  'use return states',
  'use single quotes',
  'valid, non',
  'values',
  'way might',
  'where Condition',
  'wisdom, not',
  'wrap multiple line expressions',
  'you need them',
  'your lets',
];
export default phrases;
