const phrases = [
  'make',
  'file',
  'set',
  'static',
  'exception',
  'security',
  'classes',
  'null',
  'compiler',
  'strings',
  'array',
  'reference',
  'form',
  'configuration',
  'library',
  'constructor',
  'database',
  'state',
  'performance',
  'algorithm',
  'validation',
  'interface',
  'properties',
  'complexity',
  'server',
  'go',
  'c',
  'integer',
  'scope',
  'constants',
  'client',
  'encryption',
  'd',
  'binary',
  'random',
  'pointers',
  'bitwise',
  'authentication',
  'session',
  'stack',
  'optional',
  'enum',
  'file system',
  'template',
  'iteration',
  'macros',
  'assertions',
  'regex',
  'casting',
  'scheme',
  'synchronization',
  'search',
  'actor',
  'protocols',
  'logging',
  'stream',
  'floating point',
  'oracle',
  'wrapper',
  'embedded',
  'framework',
  'converting',
  'rest',
  'collections',
  'portability',
  'flask',
  'inheritance',
  'processing',
  'lambda',
  'socket',
  '2048',
  'cyclomatic complexity',
  'container',
  'modules',
  'generator',
  'html',
  'r',
  'url',
  'closure',
  'formatting',
  'http',
  'layout',
  'javascript',
  'authorization',
  'namespaces',
  'python',
  'serialization',
  'collision',
  'reflection',
  'shell',
  'email',
  'parsing',
  'recursion',
  'assembly',
  'locking',
  'interpreter',
  'escaping',
  'installer',
  'variadic',
  'helper',
  'image',
  'callback',
  'heap',
  'overloading',
  'optimization',
  'xml',
  'tree',
  'error handling',
  'compression',
  'join',
  'iterator',
  'lookup',
  'type safety',
  'atomic',
  'lazy',
  'asynchronous',
  'singleton',
  'user interface',
  'aes',
  'https',
  'proxy',
  'generics',
  'sql',
  'mysql',
  'repository',
  'subroutine',
  'kernel',
  'smart pointers',
  'delegates',
  'unix',
  'extension methods',
  'exception handling',
  'xpath',
  'timeout',
  'mobile',
  'cache',
  'concurrency',
  'promise',
  'jwt',
  'backtracking',
  'c11',
  'console',
  'constant expression',
  'object oriented',
  'virtual machine',
  'xslt',
  'lxml',
  'ssh',
  'matrix',
  'nunit',
  'boost',
  'hashcode',
  'dice',
  'machine learning',
  'dependency injection',
  'posix',
  'stored procedure',
  'unicode',
  'timer',
  'simulation',
  'batch',
  'queue',
  'java',
  'mocks',
  'sqlalchemy',
  'prolog',
  'pandas',
  'xsd',
  'th',
  'li',
  'com',
  'amp',
  'code',
  'tr',
  'ex',
  'em',
  'el',
  'rs',
  'id',
  'int',
  'op',
  'lt',
  'wa',
  'ref',
  'def',
  'os',
  'per',
  'iv',
  'fin',
  'ps',
  'cat',
  'str',
  'val',
  'exp',
  'http',
  'href',
  'end',
  'fr',
  'fun',
  'ui',
  'value',
  'func',
  'ind',
  'data',
  'gt',
  'function',
  'eq',
  'name',
  'app',
  'form',
  '01',
  'class',
  'state',
  'return',
  'br',
  'age',
  'impl',
  'var',
  'definition',
  'case',
  'raise',
  'html',
  'statement',
  'method',
  'public',
  'sam',
  'define',
  'ip',
  'main',
  'type',
  'new',
  'sy',
  'ws',
  'port',
  'const',
  'result',
  '17',
  'source',
  'move',
  'struct',
  'num',
  'index',
  'let',
  'uri',
  'asp',
  'set',
  'defined',
  'row',
  'file',
  'exec',
  'expr',
  'obj',
  'col',
  'php',
  'sha',
  'access',
  'exc',
  'line',
  'param',
  'object',
  'string',
  'expected',
  'program',
  'format',
  'user',
  'self',
  'top',
  'char',
  'emp',
  'condition',
  'less',
  'pass',
  'lock',
  'values',
  'event',
  'always',
  'perform',
  'match',
  'point',
  'cts',
  'number',
  'foo',
  'names',
  'prod',
  'test',
  'base',
  'doc',
  'text',
  'len',
  'except',
  'block',
  'argument',
  'information',
  'sys',
  'first',
  'system',
  'try',
  'coll',
  'valid',
  'key',
  'exception',
  'answer',
  'long',
  'throw',
  'private',
  'list',
  'rows',
  'sub',
  'yes',
  'null',
  'character',
  'static',
  'p2',
  'operation',
  'product',
  'date',
  'size',
  'actor',
  'reference',
  'else',
  'soc',
  'include',
  'td',
  'boo',
  '11',
  '42',
  'declare',
  'word',
  'handle',
  'configuration',
  'break',
  'java',
  'auto',
  'files',
  'parameters',
  'iso',
  'op2',
  'field',
  'signed',
  'bit',
  'arr',
  'count',
  'cp',
  'action',
  'open',
  'back',
  'uid',
  'bool',
  'switch',
  'lim',
  'write',
  'std',
  'undef',
  'strong',
  'resource',
  'loop',
  'deprecated',
  'comment',
  '03',
  'arguments',
  'element',
  'factor',
  'import',
  'final',
  'head',
  'member',
  'operators',
  'empty',
  'path',
  'pic',
  'body',
  'literal',
  'large',
  'print',
  'array',
  'pointer',
  'sum',
  'web',
  'special',
  'trust',
  'exit',
  'alt',
  'memory',
  'stream',
  'eval',
  'flag',
  'trusted',
  'second',
  'crypt',
  'lang',
  'present',
  'report',
  'strings',
  'cgi',
  'repr',
  'message',
  'request',
  '_a',
  'constructor',
  'pattern',
  'length',
  'accept',
  'bar',
  'right',
  'script',
  'restrict',
  'boolean',
  'level',
  'elements',
  'itab',
  'interface',
  'constant',
  'pack',
  'manage',
  'protected',
  'sequence',
  'initialize',
  'extern',
  'parent',
  'equal',
  'catch',
  'resources',
  'password',
  'nested',
  'cast',
  'url',
  'namespace',
  'dest',
  'package',
  'mechanism',
  'literals',
  'component',
  'server',
  'nbsp',
  'property',
  'evaluate',
  'override',
  'blob',
  '000',
  'scope',
  'conn',
  'instances',
  'validate',
  'documentation',
  'subs',
  'never executed',
  'media',
  'delete',
  'gui',
  'sr',
  'empl',
  'algorithm',
  'thread',
  'begin',
  'forms',
  'public static',
  'zero',
  'database',
  'display',
  'double',
  'stored',
  '60',
  'js',
  'throws',
  'address',
  'comparison',
  'enum',
  'target',
  'lt th',
  '07',
  'available',
  'free',
  'byte',
  '05',
  'debug',
  'thrown',
  'words',
  'properties',
  'encrypt',
  'arbitrary',
  'puts',
  'module',
  'buffer',
  'left',
  'alternative',
  'counter',
  'day',
  'person',
  'initialization',
  'closed',
  'comma',
  'throw new',
  'integer',
  'caller',
  'complexity',
  'short',
  'directory',
  'critical',
  'compute',
  'numbers',
  'label',
  'parse',
  'validation',
  'dynamic',
  'client',
  '99',
  'crypto',
  'h3',
  'cookie',
  'select',
  'binary',
  'neutralize',
  'compare',
  'random',
  'glob',
  'virtual',
  'ssl',
  'void fun',
  'global',
  'query',
  'insecure',
  'style',
  'increment',
  'task',
  'review',
  'warn',
  'trigger',
  'initialized',
  'identifiers',
  'record',
  'continue',
  'sizeof',
  'ptr',
  'session',
  'super',
  'unused',
  'asc',
  'host',
  'checking',
  '77',
  'inputs',
  'hash',
  'primitive',
  'procedure',
  'assert',
  'template',
  'duplicate',
  'cookies',
  'page',
  'div',
  'cryptographic',
  'software uses',
  'designed',
  'entity',
  'constants',
  'desc',
  'escape',
  'condition1',
  'guid',
  'nature',
  'map',
  'curl',
  'condition2',
  'string literal',
  'keys',
  'implemented',
  'encoding',
  'optional',
  'domain',
  'link',
  'const char',
  's1',
  'args',
  'stack',
  'protocol',
  'handler',
  'unsigned',
  'promise',
  'warning',
  'float',
  'item',
  'column',
  'annotation',
  'src',
  'stop',
  'filter',
  'bits',
  'nan',
  'printf',
  'sets',
  'crypted',
  'permissions',
  'p1',
  '88',
  'letter',
  'derived',
  'abstract',
  'mail',
  'pb',
  'instant',
  'variant',
  'encryption',
  'caught',
  'fs',
  'validated',
  'creates',
  'resolve',
  'calc',
  'loops',
  'neutralizes',
  'compromise',
  'authentication',
  'release',
  'pear',
  'dot',
  'programs',
  'cipher',
  'incorrectly neutralizes',
  'tests',
  'public function',
  'typed',
  's2',
  'r2',
  'equals',
  'token',
  'child',
  'parentheses',
  'width',
  'directives',
  'negative',
  'engine',
  'v1',
  'functionality',
  'temporary',
  'configuration file',
  'section',
  'sql',
  'book',
  'privileges',
  'rsa',
  'calculate',
  'unconditional',
  'fc',
  'special elements',
  'queries',
  'structures',
  'node',
  'f1',
  'according',
  'exists',
  'c1',
  'void foo',
  'goto',
  'vec',
  'logs',
  'downstream component',
  'downstream',
  'reader',
  'owner',
  'handles',
  'forward',
  'browsers',
  'scheme',
  'reverse',
  'views',
  'identity',
  'procedures',
  'color',
  'distinct',
  'private int',
  'behaviors',
  'padding',
  'filename',
  'tree',
  'm1',
  'stores',
  'sort',
  'insert',
  'arrays',
  'terminated',
  'entities',
  'a1',
  'response',
  'uint',
  'println',
  'channel',
  'none',
  'code exec',
  'sun',
  'xml',
  'typedef',
  'caps',
  'int fun',
  'processes',
  'regex',
  'admin',
  'addresses',
  'contents',
  'others',
  'pow',
  'c2',
  'weaknesses',
  'macros',
  'username',
  'destructor',
  'inline',
  'law',
  'login',
  'endif',
  'union',
  'null pointer',
  'services',
  'join',
  'status',
  'commands',
  'synchronize',
  'magic',
  'obsolete',
  '10000',
  'logger',
  'modifying',
  'city',
  'architecture',
  'large number',
  'container',
  'certificate',
  'assignments',
  'headers',
  'closure',
  'public boolean',
  'static int',
  'cd',
  'application use',
  'horizontal',
  'child class',
  'ownership',
  'lambda',
  'prototype',
  'size_t',
  'trace',
  'const int',
  'reject',
  'parent class',
  'software contains',
  'passwords',
  'score',
  'lh',
  'ctr',
  'commit',
  'disk',
  'readonly',
  'async',
  'error message',
  'x1',
  'cursor',
  'causing',
  'power',
  'annotations',
  'regular expressions',
  'hour',
  'hostname',
  'synchronized',
  'ids',
  'signal',
  'collections',
  'license',
  'octal',
  'denominator',
  'pathname',
  'locking',
  'tls',
  'paragraph',
  'environment variables',
  'compound',
  'block contain',
  'echo',
  'digits',
  'employee',
  'volatile',
  'botan',
  'casts',
  'unique_ptr',
  'records',
  'depth',
  'apple',
  'accesses',
  'drop',
  'commented',
  'inheritance',
  'partial',
  'await',
  'amount',
  'exponent',
  'validates',
  'administrator',
  'unlock',
  'descriptor',
  'strategy',
  'strlen',
  'text block',
  'locked',
  'assembly',
  'constraint',
  'hidden',
  'floating point',
  'mixed',
  'race condition',
  'manager',
  'symbol',
  'callback',
  'archive',
  'spot',
  'incorrectly handles',
  'layer',
  'new object',
  'callb',
  'title',
  'finalize',
  'prints',
  'mutex',
  'monitor',
  'product uses',
  'deserialization',
  'noexcept',
  'file descriptor',
  'represents',
  'preprocessing',
  'attempts',
  'factory',
  'param1',
  'exchange',
  'delimiters',
  '__attribute__',
  'property name',
  'x2',
  'protection mechanism',
  'appears',
  'draw',
  'b1',
  'linear',
  'bit field',
  'params',
  'cognitive',
  'format string',
  'image',
  'hours',
  'differences',
  'p3',
  'uint32_t',
  'random number',
  'year',
  'specifications',
  'placing',
  'fruit',
  'introduces',
  'hardware',
  'paragraphs',
  'unauthorized actor',
  'builtin',
  'traffic',
  'week',
  'serializable',
  'controlling',
  'typeof',
  'groups',
  'clone',
  'uint8_t',
  'pfile',
  'scan',
  'aaa',
  'orange',
  'endpoint',
  'elif',
  'standard input',
  'email',
  'certificates',
  'substring',
  'input validation',
  'lambdas',
  'transaction',
  'executable',
  'capture',
  'smaller functions',
  'authorization',
  'codes',
  'challenge',
  'sockets',
  'declarator',
  'ctx',
  'img',
  'heap',
  'import java',
  'closures',
  'documented',
  'delegate',
  'height',
  'shared_ptr',
  'dim',
  'scale',
  'msg',
  'trivial',
  'stores sensitive',
  'errno',
  'pragma',
  'dbo',
  'raising',
  'application stores',
  'dispose',
  'blacklist',
  'b2',
  'started',
  'h1',
  'security policy',
  'fname',
  'class implement',
  'noreturn',
  'magic numbers',
  'p4',
  'birthday',
  'something_else',
  'unreachable',
  'namespaces',
  'code dynamically',
  'job',
  'quotes',
  'whitespaces',
  'int flag',
  'alpha',
  'style comments',
  'instanceof',
  'dependency',
  'contain sensitive information',
  'jail',
  'flexible',
  'string format',
  'abc',
  'persons',
  'my_table',
  'garbage',
  'i2',
  'application stores sensitive',
  'basis',
  'archive files',
  'public override void',
  'reveal',
  'empty string',
  'sections',
  'accounts',
  'certificate chain',
  'compound statement',
  'public const',
  'shell',
  'callable',
  'web browsers',
  'octal values',
  'encoded',
  'shutdown',
  'salesforce',
  'concrete',
  'remainder',
  'unnecessarily',
  'comma operator',
  'int16_t',
  'boolean equals',
  'predicted',
  'csp',
  'family',
  'mkstemp',
  'labeled',
  'int const',
  'user request',
  'command line',
  'md5',
  'divisor',
  'constexpr',
  'smtp',
  'nil',
  'hello world',
  'line arguments',
  'ripe',
  'baz',
  'persistent',
  'constrained',
  'unsigned type',
  'table1',
  'singleton',
  'iterator',
  'public method',
  'shifting',
  'stores sensitive information',
  'u8c',
  'mtx1',
  'dividend',
  'technique',
  'price',
  'code sha',
  'command line arguments',
  'put list',
  'working directory',
  'data element',
  'cleartext',
  'untrusted data',
  'subquery',
  'cobol',
  'perform assignment',
  'capabilities',
  'trusted data',
  'key exchange',
  'public var',
  'async function',
  'mock',
  'captured',
  'cache',
  'defects',
  'timeout',
  'subqueries',
  'firstname',
  'matcher',
  'shape',
  'myvar',
  'chroot',
  'copyable',
  'using string',
  'signal handler',
  'data store',
  'happened',
  'loader',
  'trivially copyable',
  'setup',
  'dummy',
  'css',
  'descriptors',
  'trivially',
  'metadata',
  'smaller methods',
  '__construct',
  'application stores sensitive information',
  'factors',
  'elseif',
  'writer',
  'block scope',
  'loggers',
  'green',
  'merge',
  'occasion',
  'nonnull',
  'properly restrict',
  'says',
  'value1',
  'nullable',
  'hand side',
  'exceptional',
  'adjacent',
  'outer class',
  'segment',
  'class contains',
  'code file',
  'multiple internal',
  'mixed content',
  'adequately',
  'program violates',
  'instead li',
  'typedefs',
  'linkage',
  'alive',
  'iostream',
  'established',
  'int field',
  'calendar',
  'jdbc',
  'obj1',
  'incorrectly validates',
  'suite',
  'greeting',
  'public static int',
  'root_dir',
  'properly verify',
  'atoi',
  'int numbers',
  'locale',
  'b3',
  'xpath',
  'character class',
  'notify',
  'cstring',
  'canonical',
  'subroutines',
  'lastname',
  'varchar',
  'decode',
  'myfunction',
  'reserved words',
  'data members',
  'foobar',
  'x3',
  'salt',
  'backup',
  'circle',
  'capitalization',
  'buffer2',
  'sprintf',
  'content security',
  'content security policy',
  'ldap',
  'special method',
  'coupled',
  'new int',
  'towns',
  'incorrectly restricts',
  'many lines',
  'critical resource',
  'pure',
  'wchar_t',
  '0l',
  'phone',
  'scoped_lock',
  'configuring loggers',
  'fuses',
  'font',
  'spoofed',
  'string password',
  'col2',
  'reentrant function',
  'employees',
  'untyped',
  'configuring',
  'member variables',
  'myclass',
  'validation form',
  'software defines',
  'virtual destructor',
  'reinterpret_cast',
  'physical',
  'mymethod',
  'carrid',
  'layers',
  'software reads',
  'th code',
  'encapsulated',
  'control element',
  'interrupted',
  'windows',
  'balance',
  'disposed',
  'function func',
  'remote server',
  'void check',
  'mylist',
  'elsif',
  'exception handling',
  'first_name',
  'string_view',
  'isolated',
  'fruits',
  'constexpr int',
  'ctime',
  'explicit call',
  'fseek',
  'validation framework',
  'transmission',
  'comment li',
  'company',
  'elt',
  'colour',
  'always evaluate',
  'comparator',
  'used inside',
  'httponly',
  'movable',
  'properly manage',
  'cmd',
  'concurrently',
  'fff',
  'timer',
  'increment clause',
  'file2',
  'asm',
  'source code contains',
  'identified',
  'sequelize',
  'fos',
  'software initialize',
  'package org',
  'quantifiers',
  'externalized',
  'dynamic_cast',
  'mcrypt_encrypt',
  'made available',
  'agents',
  'jsp',
  'int age',
  'ejb',
  'software makes',
  'userinput',
  'children',
  'referer',
  'exceptional condition',
  'process object',
  'pragma warning',
  '02d',
  'call super',
  'multiply',
  'my_var',
  'comment syntax',
  'inclusive',
  'registry',
  'relatively',
  'subprocedures',
  'file1',
  'culture',
  'matrix',
  'deserializing',
  'static_assert',
  'action1',
  'subrc',
  'last_name',
  'restricted use',
  'data manager',
  'sharing',
  'selectors',
  'package names',
  'incorrectly uses',
  'dynamic heap memory',
  'smaller subroutines',
  'heap memory',
  'cursor inside',
  'externally controlled',
  'executing code',
  'multiple trailing',
  'cloneable',
  'product exposes',
  'structured message',
  'assembly language',
  'snprintf',
  'const float',
  'specified size',
  'untrusted agents',
  'urllib',
  'external actors',
  'dynamic heap',
  'critical section',
  'string using',
  'keyword argument',
  'col3',
  'variety',
  'overly',
  'struts',
  'column1',
  'mockito',
  'principles',
  'desirable maximum',
  'encodings',
  'us_persons',
  'properly protect',
  'across multiple',
  'serializable object',
  'validation logic',
  'package names match',
  'invalid_argument',
  'xss',
  'spheres',
  'product calls',
  'buffer1',
  'db_persons',
  'structural',
  'define foo',
  'output buffer',
  'pamh',
  'fout',
  'parent element',
  'software validate',
  'offsetof',
  'operation codes',
  'ns1',
  'zero initialization',
  'pam_acct_mgmt',
  'my_variable',
  'preprocessor operators',
  'myfield',
  'metadata tag',
  'todo',
  'clients',
  'longjmp',
  'margin',
  'rownum',
  'code sequence',
  'uses operator',
  'bob',
  'servername',
  'cancel',
  'mtx2',
  'method3',
  'time_ptr',
  'software attempts',
  'back reference',
  'setjmp',
  'fourth',
  'handle input',
  '20000',
  'flexible array',
  'variable type',
  'unions',
  'joe',
  'excessively',
  'setuid',
  'plaintext password',
  'input validation framework',
  'pragma pack',
  'myint',
  'props',
  'method2',
  '08x',
  'import static',
  'rhs',
  'vararg',
  'table2',
  'mav',
  'connid',
  'pipeline',
  'unicode',
  'lock lock',
  'excessively large',
  'val1',
  'software stores sensitive information',
  'signed primitive',
  'new paragraph',
  'subprocess',
  'debugging code',
  'float64_t',
  'software stores sensitive',
  'u16a',
  'seeds',
  'release function',
  'unsigned primitive',
  'funs',
  'fooval',
  'parent classes',
  'input uses',
  'implicitly inserted',
  'uses multiple',
  'web browsers perform',
  'relatively small',
  'chip',
  'paragraph2',
  'virtual method',
  'contains data',
  'browsers perform',
  'column2',
  'branching',
  'private variable',
  'particular element',
  'data access',
  'dynamic clauses',
  'end condition',
  'explicitly authorized',
  'synchronized block',
  'int glob',
  'architectural',
  'interceptors',
  'fetch directives',
  'public object',
  'int matrix',
  'download',
  'dump',
  'another actor',
  'end exec',
  'longhand',
  'open_basedir',
  'lt li',
  'original developer',
  'program calls',
  'closedir',
  'var int',
  'respect user',
  'my_type',
  'exposes sensitive',
  'bld',
  'completely specified',
  'countries',
  'reveal sensitive',
  'neener',
  'op1',
  'paragraph1',
  'function never',
  'random1',
  'lt html',
  'action random1',
  'u16b',
  'unnecessarily large',
  'cloned mutable',
  'cloned mutable data',
  'mutable data',
  'unnecessarily large number',
  'session id',
  'expanding archive files',
  'exposes security',
  'text string',
  'shuts',
  'expanding archive',
  'expanding',
  'dpt',
  'hashlib',
  'quantitative',
  'program less',
  'put_line',
  'dosomething',
  'override public function',
  'anchors',
  'software assigns',
  '13 instead',
  'persistent cookies',
  'const long',
  'insecure permissions',
  'reads data',
  'intended buffer',
  'data past',
  '__all__',
  'product defines',
  'mystr',
  'my_macro',
  'software sets',
  'class1',
  'program less readable',
  'my_user',
  'veg',
  'conn_tab',
  'let obj1',
  'index value',
  'struct tnode',
  'internal variable',
  'equal objects',
  'specific error',
  'multiple leading',
  'protected string',
  'criterion',
  'speech',
  'tnode',
  'spatula',
  'incorrect usage',
  '_foo',
  'transformer',
  'lt result',
  'sentence',
  'uname',
  'nodiscard',
  'trailing slash',
  'code files',
  'dbms_output',
  'strawberry',
  'hidden files',
  'handles inputs',
  'cleartext within',
  'product behaves',
  'reference count',
  'revocation',
  'corresponding validation',
  'corresponding validation form',
  'structural element',
  'multiple functions',
  'class element',
  'nullable_column',
  'int int',
  'unintended results',
  'software component',
  'public protocol',
  'runnable',
  'class loader',
  'mymodule import',
  'serialization method',
  'student',
  'mymodule',
  'drop privileges',
  'public function func',
  'curl_setopt',
  'product behaves differently',
  'is_running',
  'lt interceptor',
  'product makes',
  'interceptor',
  'myarray',
  'restricts access',
  'system behavior',
  'software writes',
  'serializable data',
  'center',
  'quantitative measure',
  'variables may',
  'restrict reading',
  'comparison function',
  'code segment',
  'properly restrict reading',
  'junit5',
  'wish',
  'python class',
  'wrong ownership',
  'weakens',
  'separate standalone',
  'specific address',
  'set name',
  'authentication technique',
  'application contains',
  'rowid',
  'elif param',
  'last identity',
  'isolate system',
  'separate standalone modules',
  'standalone modules',
  'myinterface',
  'also shuts',
  'handling block',
  'seealldata',
  'pipelined',
  'manageable',
  'new environment',
  'neutralizes output',
  'directories accessible',
  'incorrectly neutralizes output',
  'httppost',
  'paragraphs contain',
  'throwable',
  'default error page',
  'display sensitive',
  'display sensitive information',
  'footer',
  'auto_ptr',
  'microfocus',
  'generic exceptions',
  'compliant comment',
  'maintain equal hashcodes',
  'directory listing',
  'inappropriately exposed',
  'potentially sensitive',
  'potentially sensitive information',
  'yielding potentially',
  'yielding potentially sensitive',
  'yielding potentially sensitive information',
  'my_number',
  'complexity measure exceeds',
  'measure exceeds',
  'functionality changes',
  'code complex',
  'io package',
  'event locations',
  'mycompany',
  'thread synchronization primitives',
  'using thread',
  'using thread synchronization',
  'using thread synchronization primitives',
  'permutation',
  'endian',
  'incorrect group',
  'administrator places',
  'blah',
  'specific value',
  'code contains callable',
  'contains callable',
  'horizontal layers',
  'architecture contains',
  'base int',
  'hurt',
  'hurt reliability',
  'exception handling block',
  'software locks',
  'invokable',
  'invokable code',
  'invokable code block',
  'invokable code block contains',
  'deserialization configuration',
  'raise_application_error',
  'trailing whitespaces',
  'application contains code',
  'static code block',
  'structure type',
  'properly distinguish',
  'accidental addition',
  'lt form',
  'requires authentication',
  'require authentication',
  'product requires authentication',
  'alternate path',
  'user_not_found',
  'customer_name',
  'initializer_list',
  'return custom error pages',
  'return custom error',
  'return custom',
  'possibly exposing sensitive information',
  'possibly exposing sensitive',
  'possibly exposing',
  'empty synchronized block',
  'empty synchronized',
  'class performs',
  'sockets instead',
  'class selectors',
  'using framework method calls',
  'using framework method',
  'using framework',
  'uses sockets instead',
  'uses sockets',
  'framework method calls',
  'directly accesses',
  'framework method',
  'directly uses sockets instead',
  'directly uses sockets',
  'directly uses',
  'application directly uses sockets',
  'application directly uses',
  'present occasion',
  'insecure behavior',
  'nullable value',
  'incorrectly neutralizes delimiters',
  'custom_exception',
  'total fixed dec',
  'total fixed',
  'declare total fixed dec',
  'declare total fixed',
  'declare total',
  'perms',
  'userid',
  'hooray',
  'says hooray',
  'l_result',
  'valuetask',
  'my_table_ids',
  'objs',
  'less secure value',
  'uncaught_exceptions',
  'accidental deletion',
  'software protects',
  'logic error',
  'neutralizes delimiters',
  'gradient',
  'func else',
  'parm',
  'collaborator',
  'objects created',
  'explicitly delimit',
  'return_status',
  't100',
  'divides',
  'product divides',
  'makes program',
  'initialize critical',
  'sort_order',
  'hover',
  'mycursor',
  'mainline',
  'mainline procedure',
  'srcstmt',
  'plist',
  'hardcoding',
  'phpunit',
  'scm',
  'makeyogurt',
  'factor authentication',
  'block creates',
  'code block creates',
  'hashcodes',
  'manage seeds',
  'correctly manage seeds',
  'correctly manage',
  'static code block creates',
  'my_date',
  'nested_function',
  'serialversionuid',
  'fun1',
  'actor without verifying',
  'peek',
  'software unlocks',
  'much self',
  'ended resource',
  'many unconditional',
  'many unconditional branches',
  'unconditional branches',
  'attackers learn',
  'user within',
  'messages help attackers learn',
  'messages help attackers',
  'messages help',
  'help attackers learn',
  'help attackers',
  'video',
  'file_uploads',
  'narg',
  'outer join',
  'initialize critical variables',
  'critical variables',
  'software contains dead code',
  'control implications',
  'adequately filter user',
  'adequately filter',
  'program accesses',
  'contains dead code',
  'print_name',
  't_mytable',
  'software accepts',
  'proper schema',
  'sslcontext',
  'computations',
  'software contains dead',
  'contains dead',
  'section1',
  'precisely predicted',
  'source code file',
  'p\u00e4ttern',
  'many operations',
  's\u00f6me',
  's\u00f6me p\u00e4ttern',
  'previous values',
  'observing previous values',
  'correctly convert',
  'observing previous',
  'observing',
  'exact value',
  'enable_dl',
  'my_package',
  'wrong handler',
  'maintain equal',
  'one concrete',
  'maintain reference',
  'variables may contain',
  'properly handle input',
  'lt label',
  'is_integral',
  'elsif param',
  'smaller procedures',
  'mytype',
  'block empty',
  'web application uses persistent',
  'uses persistent cookies',
  'uses persistent',
  'cookies contain sensitive information',
  'cookies contain sensitive',
  'cookies contain',
  'application uses persistent cookies',
  'application uses persistent',
  'reads data past',
  'realdir',
  'variables may contain sensitive',
  'may contain sensitive information',
  'software reads data',
  'may contain sensitive',
  'product calls umask',
  'incorrect argument',
  'calls umask',
  'associated serialization',
  'associated copy',
  'associated serialization method',
  'serializable data element',
  'uses several different',
  'uses several',
  'input uses several different',
  'input uses several',
  'namespace foo',
  'passing control',
  'software writes data',
  'software writes data past',
  'writes data',
  'writes data past',
  'fun2',
  'software reads data past',
  'immutable identifiers',
  'multiple trailing slash',
  'insufficient session',
  'internal slash',
  'void count',
  'multiple internal slash',
  'model validation framework',
  'model validation',
  'complex structures',
  'incorrectly handles inputs',
  'undefined unless',
  'control parameter',
  'return 10l',
  '10l',
  'comparable',
  'uncaught_exception',
  'inconsistent implementations across operating',
  'inconsistent implementations across',
  'inconsistent implementations',
  'backticks',
  'values stored',
  'good argument',
  'software modifies',
  'nchar',
  'wmode',
  'drop_table',
  'force_redirect',
  'debug interface',
  'contains virtual',
  'input expression',
  'leading slash',
  'multiple leading slash',
  'structural elements',
  'begun',
  'connection creation',
  'leaving paragraphs',
  'avoid leaving paragraphs',
  'avoid leaving',
  'product makes files',
  'makes files',
  'sufficiently restrict',
  'incorrectly restricts access',
  'properly maintain reference',
  'incorrectly releases',
  'generates numbers',
  'system settings',
  'configuration elements',
  'properly clean',
  'cross join',
  'php_sapi_name',
  'php_sapi',
  'remove temporary',
  'supporting resources',
  'availability',
  'properly isolate shared resources',
  'properly isolate shared',
  'properly isolate',
  'isolate shared resources',
  'isolate shared',
  'mutate',
  'immutable element',
  'program release',
  'across multiple architectural',
  'associated virtual destructor',
  'across multiple architectural layers',
  'resource two',
  'mon2',
  'p_string',
  'product exposes security',
  'column3',
  'sensitive values',
  'sensitive values stored',
  'proper entity',
  'a1 a2',
  'multiple architectural layers',
  'multiple architectural',
  'element across multiple architectural',
  'element across multiple',
  'element across',
  'control element across multiple',
  'control element across',
  'architectural layers',
  'associated virtual',
  'content_type',
  'int new',
  'contains references',
  'calculated using',
  'myproperty',
  'my_pow',
  'relevant documentation',
  'described within',
  'commentary',
  'program defines',
  'bbb',
  'let pi',
  'smaller sections',
  'smaller paragraphs',
  'teardown',
  'particular structural element',
  'particular structural',
  'comment started',
  'identified variables',
  'refresh',
  'inheritance level',
  'properly encode',
  'duplicate key',
  'secure design',
  'path equivalence',
  'equivalence',
  'prevents dangerous values',
  'prevents dangerous',
  'overly restrictive',
  'dangerous values',
  'i_1',
  'chain23',
  'chain1234',
  'may reveal',
  'may reveal sensitive',
  'may reveal sensitive debugging',
  'code grouping',
  'reveal sensitive debugging',
  'reveal sensitive debugging information',
  'sensitive debugging',
  'sensitive debugging information',
  'implementations across operating systems',
  'implementations across operating',
  'implementations across',
  'elseif param',
  'using sockets',
  'font family',
  'product expects',
  'backup file',
  'orderby',
  'parameterized using',
  'externalized instead',
  'john',
  'w_alvvr',
  'display something',
  'data representation',
  'callables',
  'friend',
  'concrete class',
  'software detects',
  'one concrete class',
  'work safely',
  'foo foo',
  'system compromise',
  'iserializable',
  'plaintext may result',
  'sensitive hardware',
  'sensitive hardware module',
  'sensitive hardware module contains',
  'performing sensitive operations',
  'performing sensitive',
  'sends non',
  'program sends non',
  'program sends',
  'cryptographic signature',
  'incorrectly verifies',
  'season',
  'employee name',
  'testcase',
  'tuesday',
  'encrypt sensitive',
  'another sphere',
  'plaintext may',
  '_make',
  'input buffer',
  'established principles',
  'singleton pattern',
  'multithreaded environment',
  'proscribed',
  'modifying code',
  'no_data_found',
  'relatively small space',
  'small space',
  'do_first',
  'input contains',
  'incomplete functionality',
  'default_value',
  'software interfaces',
  'define inputs',
  'adequately define inputs',
  'adequately define',
  'cx_3',
  'lookahead',
  'equal hashcodes',
  'resource within',
  'company policy',
  'one signal',
  'domain policy',
  'product mixes trusted',
  'product mixes',
  'mixes trusted',
  'mixes',
  'my_form',
  'trivial encoding',
  'show_name',
  'fullname',
  'empty lines',
  'name1',
  'server error message',
  'server error',
  'network failure',
  'rectangle',
  'policy file',
  'includes domains',
  'domain policy file',
  'implicit intent',
  'transmitting',
  'transmitting sensitive',
  'software uses multiple',
  'script syntax',
  'alternate script syntax',
  'alternate script',
  'setting error',
  'setting error message',
  'using groups',
  'has_errors',
  'control spheres',
  'product prevent',
  'section names',
  'dept_id',
  'product exposes sensitive information',
  'product exposes sensitive',
  'exposes sensitive information',
  'have_money',
  'have_time',
  'take_vacation',
  'code associated',
  'software uses multiple resources',
  'transmitting sensitive data',
  'unique identifiers',
  'product violates',
  'product violates well',
  'violates well',
  'varchar2',
  'allow_url_fopen',
  'wrong action',
  'form indicates',
  'element selectors',
  'conditional logic',
  'unused validation',
  'case tuesday',
  'smaller subs',
  'unused validation form',
  'unused validation form indicates',
  'validation form indicates',
  'week year',
  'uses multiple resources',
  'signal handlers',
  'date form',
  'still intended',
  'program releases',
  'tostring',
  'module contains semiconductor',
  'module contains semiconductor defects',
  'semiconductor',
  'using string concatenation operations',
  'using string concatenation',
  'semiconductor defects',
  'text string using string',
  'text string using',
  'string using string concatenation',
  'string using string',
  'string concatenation operations',
  'immutable text string using',
  'immutable text string',
  'immutable text',
  'concatenation operations',
  'initializer_list constructor',
  'module contains',
  'causes incorrect',
  'causes incorrect logic',
  'published specifications',
  '123456789',
  'contains semiconductor',
  'contains semiconductor defects',
  'hardware module',
  'parent class contains',
  'bar2',
  'hardware module contains',
  'function according',
  'incorrect logic',
  'hardware module contains semiconductor',
  'myattribute',
  'precedence causes incorrect logic',
  'precedence causes incorrect',
  'precedence causes',
  'operator precedence causes incorrect',
  'operator precedence causes',
  'certain conditions',
];
export default phrases;
