export const modalDetails = [
  {
    content: 'You can go to your Personal or Organization Profile, Activity Log and click “Snapshot for Portfolio”',
    img: '/img/portfolio/portfolio-guide-1.png',
    alt: 'guide-1',
    width: '456px',
    height: '248px',
    leftColumn: 'is-8',
    rightColumn: '',
    contentMargin: 'mt-50',
  },
  {
    content: 'Write the best title to show your experience and write a description to show your progress.',
    img: '/img/portfolio/portfolio-guide-2.png',
    alt: 'guide-2',
    width: '319px',
    height: '293px',
    leftColumn: '',
    rightColumn: 'is-7',
    contentMargin: 'mt-80',
  },
  {
    title: 'Amazing!',
    content: 'Now your portfolio will be shown here!',
    img: '/img/portfolio/portfolio-guide-3.png',
    alt: 'guide-3',
    width: '301px',
    height: '308px',
    leftColumn: 'is-7',
    rightColumn: '',
    contentMargin: 'mt-100',
  },
];
