import adminUsers from './admin/users';
import analysis from './analysis';
import auth from './auth';
import collections from './comments/collections';
import credentials from './credentials';
import endGuides from './comments/engGuides';
import github from './identity/github';
import health from './shared/health';
import invitations from './invitations';
import notifications from './notifications';
import organizations from './organizations';
import portfolios from './portfolios';
import repoSync from './repoSync';
import reports from './reports';
import repositories from './repositories';
import roles from './roles';
import searchQueries from './admin/searchQueries';
import smartComments from './comments/smartComments';
import snapshots from './snapshots';
import sources from './sources';
import suggestedComments from './comments/suggestedComments';
import support from './support';
import tags from './comments/tags';
import userRoles from './userRoles';
import users from './users';

export default function attachRoutes(app, passport) {
  analysis(app, passport);
  auth(app, passport);
  collections(app, passport);
  endGuides(app, passport);
  smartComments(app, passport);
  suggestedComments(app, passport);
  tags(app, passport);
  credentials(app, passport);
  github(app);
  health(app);
  invitations(app, passport);
  notifications(app, passport);
  organizations(app, passport);
  portfolios(app, passport);
  reports(app, passport);
  repositories(app, passport);
  repoSync(app, passport);
  sources(app, passport);
  users(app, passport);
  adminUsers(app, passport);
  searchQueries(app, passport);
  snapshots(app, passport);
  support(app, passport);
  roles(app, passport);
  userRoles(app, passport);
}
