export const REQUEST_CREATE_INVITE = 'REQUEST_CREATE_INVITE';
export const REQUEST_CREATE_INVITE_SUCCESS = 'REQUEST_CREATE_INVITE_SUCCESS';
export const REQUEST_CREATE_INVITE_ERROR = 'REQUEST_CREATE_INVITE_ERROR';
export const REQUEST_FETCH_INVITE = 'REQUEST_FETCH_INVITE';
export const REQUEST_FETCH_INVITE_SUCCESS = 'REQUEST_FETCH_INVITE_SUCCESS';
export const REQUEST_FETCH_INVITE_ERROR = 'REQUEST_FETCH_INVITE_ERROR';
