openapi: 3.0.0
info:
  title: Credential's API
  description: Credentials
  version: 1.0.0
servers:
  - url: http://localhost:3001
    description: Local Dev
  - url: https://api-qa.semasoftware.com
    description: QA
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - bearerAuth: []
paths:
  /v1/credentials/:
    post:
      summary: create credentials
      operationId: create
      requestBody:
        content:
          application/json:
            schema:
              properties:
                name:
                  type: string
      responses:
        200:
          content:
            application/json:
              schema:
                properties:
                  credentials:
                    type: string
          description: created credentials
        400:
          description: bad input parameter
    get:
      summary: get cretendials
      operationId: get
      responses:
        200:
          description: get cretendials
        400:
          description: bad input parameter