export const ADD_SEMA_COMPONENTS = 'ADD_SEMA_COMPONENTS';
export const TOGGLE_TAG_MODAL = 'TOGGLE_TAG_MODAL';
export const CLOSE_ALL_MODALS = 'CLOSE_ALL_MODALS';
export const UPDATE_SELECTED_EMOJI = 'UPDATE_SELECTED_EMOJI';
export const UPDATE_SELECTED_TAGS = 'UPDATE_SELECTED_TAGS';
export const TOGGLE_SEARCH_MODAL = 'TOGGLE_SEARCH_MODAL';
export const ADD_SUGGESTED_TAGS = 'ADD_SUGGESTED_TAGS';
export const UPDATE_SELECTED_TAG_WITH_SUGGESTION =
  'UPDATE_SELECTED_TAG_WITH_SUGGESTION';
