export const ADD_SEMABAR = 'ADD_SEMABAR';
export const TOGGLE_TAG_MODAL = 'TOGGLE_TAG_MODAL';
export const CLOSE_ALL_MODALS = 'CLOSE_ALL_MODALS';
export const UPDATE_SELECTED_EMOJI = 'UPDATE_SELECTED_EMOJI';
export const UPDATE_SELECTED_TAGS = 'UPDATE_SELECTED_TAGS';
