export const ADD_SEMA_COMPONENTS = 'ADD_SEMA_COMPONENTS';
export const TOGGLE_TAG_MODAL = 'TOGGLE_TAG_MODAL';
export const CLOSE_ALL_MODALS = 'CLOSE_ALL_MODALS';
export const UPDATE_SELECTED_EMOJI = 'UPDATE_SELECTED_EMOJI';
export const UPDATE_SELECTED_TAGS = 'UPDATE_SELECTED_TAGS';
export const TOGGLE_SEARCH_MODAL = 'TOGGLE_SEARCH_MODAL';
export const ADD_SUGGESTED_TAGS = 'ADD_SUGGESTED_TAGS';
export const UPDATE_SELECTED_TAG_WITH_SUGGESTION =
  'UPDATE_SELECTED_TAG_WITH_SUGGESTION';
export const TOGGLE_GLOBAL_SEARCH_MODAL = 'TOGGLE_GLOBAL_SEARCH_MODAL';
export const TOGGLE_GLOBAL_SEARCH_LOADING = 'TOGGLE_GLOBAL_SEARCH_LOADING';
export const ON_INPUT_GLOBAL_SEARCH = 'ON_INPUT_GLOBAL_SEARCH';
export const RESET_SEMA_STATES = 'RESET_SEMA_STATES';
export const UPDATE_GITHUB_TEXTAREA = 'UPDATE_GITHUB_TEXTAREA';
export const UPDATE_SEMA_USER = 'UPDATE_SEMA_USER';
