export const AUTHENTICATE_REQUEST = 'AUTHENTICATE_REQUEST';
export const AUTHENTICATE = 'AUTHENTICATE';
export const AUTHENTICATE_FAILURE = 'AUTHENTICATE_FAILURE';
export const DEAUTHENTICATE = 'DEAUTHENTICATE';
export const HYDRATE_USER = 'HYDRATE_USER';
