#!/usr/bin/env groovy
@Library('customSlackLibrary') _
pipeline {
    agent {
        docker {
            image 'cimg/node:15.14.0'
            args '-u root --privileged --net host'
        }
    }

    options {
        buildDiscarder(logRotator(numToKeepStr: '20'))
        timestamps()
    }

    parameters {
        string(name: 'ENVIRONMENT', description: 'The name of environment for building')
        string(name: 'BRANCH_NAME', description: 'The name of branch for building')
    }

    stages {
        stage('Kick off codebuild project') {
            steps {
                awsCodeBuild credentialsType: 'keys', projectName: "${params.ENVIRONMENT}-scr-themis-build", region: 'us-east-1', sourceControlType: 'jenkins'
            }
        }
    }

    post {
        failure {
            slackSendsFail(env.JOB_NAME, params.BRANCH_NAME, BUILD_URL)
        }
        
        always{
            cleanWs()
        }
    }
}
