export const REQUEST_FETCH_SEARCH_QUERIES = 'REQUEST_FETCH_SEARCH_QUERIES';
export const REQUEST_FETCH_SEARCH_QUERIES_SUCCESS = 'REQUEST_FETCH_SEARCH_QUERIES_SUCCESS';
export const REQUEST_FETCH_SEARCH_QUERIES_ERROR = 'REQUEST_FETCH_SEARCH_QUERIES_ERROR';
