FROM node:12.15.0-alpine

WORKDIR /usr/app
COPY ./package*.json ./

RUN npm ci
RUN npm prune --production

RUN npm install -g migrate pm2

COPY ./ ./

EXPOSE 3001
USER node

ENV NODE_ENV production

# Run npm start script with PM2 when container starts
CMD [ "pm2-runtime", "npm", "--", "start" ]
