FROM node:12.15.0-alpine

RUN apk add --update --no-cache \
    python \
    make \
    g++

WORKDIR /usr/app
COPY ./.env ./.env
COPY ./package*.json ./

ENV NODE_ENV development
ENV PATH /usr/app/node_modules/.bin:$PATH
RUN npm install  

EXPOSE 3001

CMD ["npm", "start"]
