FROM node:12.15.0-alpine3.11

RUN apk add --update --no-cache \
    python~=2.7 \
    make~=4.2 \
    g++~=9.3

WORKDIR /usr/app
COPY ./.env ./.env
COPY ./package*.json ./

ENV NODE_ENV development
ENV PATH /usr/app/node_modules/.bin:$PATH
RUN npm install  

EXPOSE 3001

CMD ["npm", "start"]
