FROM node:12.15.0-alpine

RUN apk add --update --no-cache \
    python \
    make \
    g++

WORKDIR /usr/app
COPY ./.env ./.env
COPY ./package*.json ./

ENV NODE_ENV development
RUN npm install -g --save-dev nodemon @babel/cli @babel/core @babel/node @babel/preset-env
RUN npm install --save-dev nodemon @babel/cli @babel/core @babel/node @babel/preset-env
RUN npm install  

EXPOSE 3001

CMD ["npm", "start"]
