export const REQUEST_FETCH_USER_SNAPSHOTS = "REQUEST_FETCH_USER_SNAPSHOTS";
export const REQUEST_FETCH_USER_SNAPSHOTS_SUCCESS =
  "REQUEST_FETCH_USER_SNAPSHOTS_SUCCESS";
export const REQUEST_FETCH_USER_SNAPSHOTS_ERROR =
  "REQUEST_FETCH_USER_SNAPSHOTS_ERROR";
export const REQUEST_UPDATE_SNAPSHOT = "REQUEST_UPDATE_SNAPSHOT";
export const REQUEST_UPDATE_SNAPSHOT_SUCCESS =
  "REQUEST_UPDATE_SNAPSHOT_SUCCESS";
export const REQUEST_UPDATE_SNAPSHOT_ERROR = "REQUEST_UPDATE_SNAPSHOT_ERROR";
export const REQUEST_DELETE_SNAPSHOT = "REQUEST_DELETE_SNAPSHOT";
export const REQUEST_DELETE_SNAPSHOT_SUCCESS =
  "REQUEST_DELETE_SNAPSHOT_SUCCESS";
export const REQUEST_DELETE_SNAPSHOT_ERROR = "REQUEST_DELETE_SNAPSHOT_ERROR";
export const REQUEST_ADD_SNAPSHOT_TO_PORTFOLIO = 'REQUEST_ADD_SNAPSHOT_TO_PORTFOLIO';
export const REQUEST_CREATE_SNAPSHOT = "REQUEST_CREATE_SNAPSHOT";
export const REQUEST_CREATE_SNAPSHOT_SUCCESS =
  "REQUEST_CREATE_SNAPSHOT_SUCCESS";
export const REQUEST_CREATE_SNAPSHOT_ERROR = "REQUEST_CREATE_SNAPSHOT_ERROR";