name: Creating release candidate
on:
  schedule:
    - cron: '*/5 * * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v2
      - run: |
          DATE=$(date +"%Y-%m-%d")
          git checkout -b release-${DATE}
          git config user.name github-actions
          git config user.email github-actions@github.com
          git push
          test=test
