name: Delete old release branches
on:
  schedule:
    - cron: '0 12 * * 0' # At 12:00 PM, only on Sunday. UTC 
  workflow_dispatch: 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: delete old release branches
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git pull --all
          git branch -r | grep -v '\->' | sed "s,\x1B\[[0-9;]*[a-zA-Z],,g" | grep -e 'release.*' | while read remote; do git branch --track "${remote#origin/}" "$remote"; done 
          
          for k in $(git branch --list "release-*" | sed /\*/d); do 
          if [ -z "$(git log -1 --before='1 week ago' -s $k)" ]; then
            echo $k
          fi
          done
        shell: bash {0}
