name: Linter
on:
  - pull_request

jobs:
  set_changed_services:
    name: Triage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get list of changed files
        uses: jitterbit/get-changed-files@v1
        id: files
      - name: Get changed services
        id: changed_services
        run: |
          changed_files="${{ steps.files.outputs.added_modified }}"
          changed_services=()

          for directory in apollo adonis themis web; do
            if grep -E -q '\b'$directory/ <<< $changed_files; then
              changed_services+=($directory)
            fi
          done

          json_result=$(jq -nc '$ARGS.positional' --args ${changed_services[@]})

          echo ::set-output name=matrix::"$json_result"
    outputs:
      matrix: ${{ steps.changed_services.outputs.matrix }}
      changed_files: ${{ steps.files.outputs.added_modified }}

  lint:
    name: Lint ${{ matrix.service }}
    needs: set_changed_services
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        service: ${{ fromJson(needs.set_changed_services.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'npm'
          cache-dependency-path: ${{ matrix.service }}/package-lock.json
      - name: Install modules
        run: npm ci
        working-directory: ${{ matrix.service }}
      - name: Lint
        run: ./scripts/lint ${{ matrix.service }} ${{ needs.set_changed_services.outputs.changed_files }}
