#!/usr/bin/env groovy
pipeline {
    agent {
        docker {
            image 'cimg/base:2020.01'
            args '-u root --privileged --net host'
        }
    }

    options {
        buildDiscarder(logRotator(numToKeepStr: '10'))
        disableConcurrentBuilds()
        retry(2)
        timestamps()
    }

    stages {
        stage('Install dependencies') {
            steps {
                sh 'sudo apt-get update -y && sudo apt-get install -y jq awscli'
            }
        }

        stage('Create phoenix profile for aws cli') {
            steps {
                script {
                    release_regex = '(release.*|DVPS-268)'
                    switch (GIT_BRANCH) {
                    case 'master':
                            ENVIRONMENT = 'prod'
                            break
                    case ['qa']:
                            ENVIRONMENT = 'qa'
                            break
                    case ['qa1']:
                            ENVIRONMENT = 'qa1'
                            break
                    case ~/$release_regex/:
                            ENVIRONMENT = 'staging'
                            break
                    }
                    sh "echo $ENVIRONMENT"
                }
            // withAWS(role:'jenkins-role-to-assume') {
            //     sh 'aws s3 ls'
            // }
            }
        }
    }
}
